"""
Train NNUE on self-play positions generated by generate_selfplay.py.

Input CSV format:
    fen,result
    result: 1.0=White won, 0.5=draw, 0.0=Black won

Architecture:  NNUEModel  (app/engine/nnue.py)
    768 → 256 → 32 → 32 → 1   (ClippedReLU activations)
    Two perspectives: (STM features, opponent features) both (batch, 768)

Loss:      MSE( sigmoid(output), stm_result )
           stm_result = result       if White to move
           stm_result = 1 - result   if Black to move
           This trains the model to predict P(side-to-move wins), which is
           identical to the convention the NNUEEvaluator already uses.

Saves:     backend/models/nnue_selfplay.pt   (best val-loss checkpoint)

Run from backend/:
    python scripts/train_nnue_selfplay.py
    python scripts/train_nnue_selfplay.py --csv data/selfplay_positions.csv
"""

from __future__ import annotations

import argparse
import csv
import random
import sys
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

# Ensure backend/ is on sys.path so `app` is importable.
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

import chess  # noqa: E402
from app.engine.nnue import NNUEModel, board_to_features  # noqa: E402

_DEFAULT_CSV    = "data/selfplay_positions.csv"
_DEFAULT_OUTPUT = "models/nnue_selfplay.pt"
_BATCH_SIZE     = 2048
_MAX_EPOCHS     = 30
_PATIENCE       = 5
_LR             = 0.001
_VAL_SPLIT      = 0.1


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class SelfPlayDataset(Dataset[tuple[torch.Tensor, torch.Tensor, torch.Tensor]]):
    """
    Loads (fen, result) pairs and encodes them for NNUEModel.

    Each item:  (stm_feat, opp_feat, stm_result)
      stm_feat   — (768,) float32, side-to-move perspective
      opp_feat   — (768,) float32, opponent perspective (mirrored)
      stm_result — float32 scalar; P(STM wins): 1.0 / 0.5 / 0.0

    Using STM-first order matches NNUEEvaluator's inference convention, so
    the saved weights are immediately compatible without any surgery.
    """

    def __init__(self, rows: list[tuple[str, float]]) -> None:
        self._rows = rows

    def __len__(self) -> int:
        return len(self._rows)

    def __getitem__(
        self, idx: int
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        fen, result = self._rows[idx]
        board = chess.Board(fen)
        wf, bf = board_to_features(board)          # White-perspective, Black-perspective

        if board.turn == chess.WHITE:
            stm_feat, opp_feat = wf, bf
            stm_result = result
        else:
            stm_feat, opp_feat = bf, wf
            stm_result = 1.0 - result              # flip to STM perspective

        return stm_feat, opp_feat, torch.tensor(stm_result, dtype=torch.float32)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _load_csv(path: Path) -> list[tuple[str, float]]:
    """Read fen,result rows; skip the header and any malformed lines."""
    rows: list[tuple[str, float]] = []
    with path.open(newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        next(reader, None)                         # skip header
        for row in reader:
            if len(row) < 2 or not row[0].strip():
                continue
            try:
                rows.append((row[0].strip(), float(row[1])))
            except ValueError:
                continue
    return rows


# ---------------------------------------------------------------------------
# Train / eval helpers
# ---------------------------------------------------------------------------

def _run_epoch(
    model: NNUEModel,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer | None,
    device: torch.device,
) -> float:
    """
    Run one train or eval epoch.  Pass optimizer=None for eval.
    Returns mean MSE loss over all samples.
    """
    is_train = optimizer is not None
    model.train(is_train)
    total_loss = 0.0
    total_samples = 0

    ctx = torch.enable_grad() if is_train else torch.no_grad()
    with ctx:
        for stm_feat, opp_feat, target in loader:
            stm_feat = stm_feat.to(device)
            opp_feat = opp_feat.to(device)
            target   = target.to(device)

            output     = model(stm_feat, opp_feat).squeeze(1)   # (batch,)
            prediction = torch.sigmoid(output)                   # → [0, 1]
            loss       = F.mse_loss(prediction, target)

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            total_loss    += loss.item() * len(target)
            total_samples += len(target)

    return total_loss / total_samples


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train NNUEModel on self-play game results."
    )
    parser.add_argument(
        "--csv", default=_DEFAULT_CSV,
        help=f"Input CSV path (default: {_DEFAULT_CSV})",
    )
    parser.add_argument(
        "--output", default=_DEFAULT_OUTPUT,
        help=f"Output weights path (default: {_DEFAULT_OUTPUT})",
    )
    parser.add_argument("--epochs",   type=int,   default=_MAX_EPOCHS)
    parser.add_argument("--batch",    type=int,   default=_BATCH_SIZE)
    parser.add_argument("--lr",       type=float, default=_LR)
    parser.add_argument("--patience", type=int,   default=_PATIENCE)
    args = parser.parse_args()

    csv_path    = Path(args.csv)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Load and split data
    # ------------------------------------------------------------------
    print(f"Loading {csv_path}…")
    if not csv_path.exists():
        print(f"ERROR: {csv_path} not found. Run generate_selfplay.py first.")
        sys.exit(1)

    rows = _load_csv(csv_path)
    if not rows:
        print("ERROR: No valid rows loaded. Check the CSV format.")
        sys.exit(1)
    print(f"Loaded {len(rows):,} positions")

    random.shuffle(rows)
    val_size   = max(1, int(len(rows) * _VAL_SPLIT))
    val_rows   = rows[:val_size]
    train_rows = rows[val_size:]
    print(f"Split: {len(train_rows):,} train / {len(val_rows):,} val")

    # Result distribution (sanity check)
    wins   = sum(1 for _, r in rows if r == 1.0)
    draws  = sum(1 for _, r in rows if r == 0.5)
    losses = sum(1 for _, r in rows if r == 0.0)
    print(f"Result dist: W={wins:,} D={draws:,} L={losses:,}")

    # ------------------------------------------------------------------
    # DataLoaders — num_workers=0 avoids Windows multiprocessing issues
    # ------------------------------------------------------------------
    train_loader = DataLoader(
        SelfPlayDataset(train_rows),
        batch_size=args.batch, shuffle=True, num_workers=0,
    )
    val_loader = DataLoader(
        SelfPlayDataset(val_rows),
        batch_size=args.batch, shuffle=False, num_workers=0,
    )

    # ------------------------------------------------------------------
    # Model, optimiser
    # ------------------------------------------------------------------
    device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model     = NNUEModel().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    print(f"\nDevice: {device}")
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")
    print(f"Batch size: {args.batch}  |  LR: {args.lr}  |  Max epochs: {args.epochs}\n")

    # ------------------------------------------------------------------
    # Training loop
    # ------------------------------------------------------------------
    best_val_loss   = float("inf")
    patience_count  = 0

    for epoch in range(1, args.epochs + 1):
        train_loss = _run_epoch(model, train_loader, optimizer, device)
        val_loss   = _run_epoch(model, val_loader,   None,      device)

        marker = ""
        if val_loss < best_val_loss:
            best_val_loss  = val_loss
            patience_count = 0
            torch.save(model.state_dict(), output_path)
            marker = " ✓"
        else:
            patience_count += 1

        patience_str = (
            f"  (patience {patience_count}/{args.patience})"
            if patience_count > 0 else ""
        )
        print(
            f"Epoch {epoch:2d}/{args.epochs} | "
            f"train={train_loss:.4f}  val={val_loss:.4f}"
            f"{marker}{patience_str}"
        )

        if patience_count >= args.patience:
            print(
                f"\nEarly stopping — no val improvement for {args.patience} epochs."
            )
            break

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    print(f"\nBest val loss: {best_val_loss:.4f}")
    print(f"Saved to {output_path}")


if __name__ == "__main__":
    main()
