"""
SPRT Validation: NNUE Pyro vs Classical Pyro

Plays N games with alternating colors.  Both engines use the same search
(depth 4, alpha-beta, NMP, LMR, AW) — the only difference is the eval function:
  NNUE engine    : NNUEEvaluator(nnue_selfplay.pt).evaluate()
  Classical engine: tal_style_eval()

Alternation: NNUE plays White in odd games, Black in even games.
This eliminates color bias from the final score.

Verdict: PASS if NNUE scores >= 55%, FAIL otherwise.

Run from backend/:
    python scripts/validate_nnue.py
    python scripts/validate_nnue.py --games 2000 --nnue models/nnue_selfplay.pt
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import chess

# Ensure backend/ is importable as a package root.
_BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

# Patch _TIME_LIMIT before any search call.
# 0.1s keeps each of the 2000 games fast enough to finish overnight.
from app.engine import search as _search_module  # noqa: E402
_search_module._TIME_LIMIT = 0.1

from app.engine import search                    # noqa: E402
from app.engine.evaluate import tal_style_eval   # noqa: E402
from app.engine.nnue import NNUEEvaluator        # noqa: E402

_DEFAULT_GAMES   = 2000
_DEFAULT_NNUE    = "models/nnue_selfplay.pt"
_DEFAULT_DEPTH   = 4
_MAX_HALF_MOVES  = 160    # 80 full moves — declare draw if exceeded
_PASS_THRESHOLD  = 55.0   # % score required for PASS


# ---------------------------------------------------------------------------
# Eval function wrapper
# ---------------------------------------------------------------------------

def _make_nnue_eval(evaluator: NNUEEvaluator):
    """
    Return a search-compatible eval_fn that calls the NNUE evaluator.

    NNUEEvaluator.evaluate() returns float | None.  None only occurs when
    no weights are loaded; after the availability check in main() this path
    is unreachable, but the tal_style_eval fallback keeps the function safe.
    """
    def _eval(board: chess.Board) -> float:
        score = evaluator.evaluate(board)
        return score if score is not None else float(tal_style_eval(board))
    return _eval


# ---------------------------------------------------------------------------
# Single game
# ---------------------------------------------------------------------------

def play_game(
    white_eval_fn,
    black_eval_fn,
    depth: int,
) -> float:
    """
    Play one game to completion.

    Each move is generated by calling search.best_move() with the eval function
    corresponding to the side to move.  The global TT, killers, and history are
    cleared at the start of each best_move() call, so neither engine leaks state
    to the other.

    Returns the result from White's perspective:
        1.0 = White wins, 0.5 = draw, 0.0 = Black wins
    """
    board = chess.Board()

    for _ in range(_MAX_HALF_MOVES):
        if board.is_game_over():
            break

        fen     = board.fen()
        eval_fn = white_eval_fn if board.turn == chess.WHITE else black_eval_fn
        uci, _  = search.best_move(fen, depth=depth, eval_fn=eval_fn)

        if not uci:
            break  # no legal moves; game_over should have caught this

        move = chess.Move.from_uci(uci)
        if move not in board.legal_moves:
            break  # safety guard

        board.push(move)

    if board.is_checkmate():
        # Side to move has been mated.
        return 0.0 if board.turn == chess.WHITE else 1.0

    return 0.5   # stalemate, repetition, 50-move, insufficient material, or cap


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="SPRT validation: NNUE Pyro vs Classical Pyro."
    )
    parser.add_argument(
        "--games", type=int, default=_DEFAULT_GAMES,
        help=f"Number of games to play (default: {_DEFAULT_GAMES})",
    )
    parser.add_argument(
        "--nnue", default=_DEFAULT_NNUE,
        help=f"Path to NNUE weights file (default: {_DEFAULT_NNUE})",
    )
    parser.add_argument(
        "--depth", type=int, default=_DEFAULT_DEPTH,
        help=f"Search depth for both engines (default: {_DEFAULT_DEPTH})",
    )
    args = parser.parse_args()

    nnue_path = Path(args.nnue)
    if not nnue_path.exists():
        print(f"ERROR: NNUE weights not found at {nnue_path}")
        print("Run train_nnue_selfplay.py first.")
        sys.exit(1)

    # NNUEEvaluator prints its own load message.
    print(f"Loading NNUE from {nnue_path}…")
    evaluator = NNUEEvaluator(model_path=str(nnue_path))
    if not evaluator.available:
        print("ERROR: Could not load NNUE weights (model returned unavailable).")
        sys.exit(1)

    nnue_eval_fn      = _make_nnue_eval(evaluator)
    classical_eval_fn = tal_style_eval

    print(
        f"\nNNUE Pyro vs Classical Pyro"
        f" — {args.games} games, depth {args.depth}, 0.1s/move\n"
        f"{'─' * 60}"
    )

    nnue_wins   = 0
    draws       = 0
    class_wins  = 0
    game_times: list[float] = []

    for game_num in range(1, args.games + 1):
        nnue_is_white = (game_num % 2 == 1)   # odd=NNUE White, even=NNUE Black

        if nnue_is_white:
            white_fn, black_fn = nnue_eval_fn, classical_eval_fn
        else:
            white_fn, black_fn = classical_eval_fn, nnue_eval_fn

        t0           = time.monotonic()
        white_result = play_game(white_fn, black_fn, depth=args.depth)
        elapsed      = time.monotonic() - t0
        game_times.append(elapsed)

        # Translate White-perspective result → NNUE-perspective result.
        nnue_result  = white_result if nnue_is_white else (1.0 - white_result)

        if nnue_result == 1.0:
            nnue_wins  += 1
            outcome     = "NNUE wins"
        elif nnue_result == 0.0:
            class_wins += 1
            outcome     = "Classical wins"
        else:
            draws      += 1
            outcome     = "Draw"

        running_pct = (nnue_wins + 0.5 * draws) / game_num * 100

        if nnue_is_white:
            matchup = "NNUE White vs Classical Black"
        else:
            matchup = "Classical White vs NNUE Black"

        print(
            f"Game {game_num:4d}/{args.games}: {matchup} → {outcome}"
            f"  [{running_pct:.1f}%]"
        )

    # ------------------------------------------------------------------
    # Final report
    # ------------------------------------------------------------------
    total_score = nnue_wins + 0.5 * draws
    score_pct   = total_score / args.games * 100
    passed      = score_pct >= _PASS_THRESHOLD
    avg_time    = sum(game_times) / len(game_times)
    total_min   = sum(game_times) / 60

    print(f"\n{'═' * 60}")
    print(
        f"NNUE: W={nnue_wins}  D={draws}  L={class_wins}"
        f"  ({score_pct:.1f}% score)"
    )
    print(f"Avg game: {avg_time:.1f}s  |  Total: {total_min:.1f}min")
    print(f"{'═' * 60}")

    if passed:
        print(
            f"PASS ✅  (>= {_PASS_THRESHOLD:.0f}%)"
            f"  — NNUE is stronger; enable it in model.py"
        )
    else:
        gap = _PASS_THRESHOLD - score_pct
        print(
            f"FAIL ❌  (< {_PASS_THRESHOLD:.0f}%, gap = {gap:.1f}%)"
            f"  — needs more self-play data or retraining"
        )

    print(f"{'═' * 60}")
    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
