/**
 * Chess opening lookup table — sourced from the Lichess chess-openings dataset.
 * https://github.com/lichess-org/chess-openings
 *
 * Each entry maps an ordered SAN move sequence to an ECO opening name.
 * For each unique name the shortest move sequence is stored, so openings
 * are recognised at the earliest possible position. Entries are sorted
 * longest-first so the most specific variation wins when multiple
 * prefixes match the current history.
 */

interface Opening {
  moves: string[]
  name: string
}

const OPENINGS: Opening[] = [
  { moves: ['e4', 'Nf6', 'e5', 'Ng8', 'd4', 'f5'], name: 'Alekhine Defense: Brooklyn Variation, Everglades Variation' },
  { moves: ['e4', 'Nf6', 'e5', 'Ne4', 'd4', 'f6'], name: 'Alekhine Defense: Mokele Mbembe, Modern Line' },
  { moves: ['e4', 'Nf6', 'e5', 'Ne4', 'd4', 'e6'], name: 'Alekhine Defense: Mokele Mbembe, Vavra Defense' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'b5'], name: 'Alekhine Defense: O\'Sullivan Gambit' },
  { moves: ['e4', 'Nf6', 'Nc3', 'd5', 'exd5', 'c6'], name: 'Alekhine Defense: Scandinavian Variation, Geschev Gambit' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'c4', 'Nf4'], name: 'Alekhine Defense: The Squirrel' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5'], name: 'Benko Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e5'], name: 'Benoni Defense: Czech Benoni Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'c5', 'd5', 'c4'], name: 'Benoni Defense: Hawk Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'd6'], name: 'Benoni Defense: Hromádka System' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6'], name: 'Benoni Defense: Modern Variation' },
  { moves: ['d4', 'c5', 'd5', 'd6', 'Nc3', 'g6'], name: 'Benoni Defense: Old Benoni, Schmid Variation' },
  { moves: ['d4', 'c5', 'd5', 'e5', 'e4', 'd6'], name: 'Benoni Defense: Semi-Benoni' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'dxc5', 'e6'], name: 'Benoni Defense: Weenink Variation' },
  { moves: ['d4', 'c5', 'd5', 'Nf6', 'Nc3', 'Qa5'], name: 'Benoni Defense: Woozle' },
  { moves: ['d4', 'c5', 'Nf3', 'cxd4', 'b4', 'e5'], name: 'Benoni Defense: Zilbermints-Benoni Gambit, Tamarkin Countergambit' },
  { moves: ['e4', 'c5', 'f4', 'd5', 'Nf3', 'dxe4'], name: 'Bird Opening: Dutch Variation, Batavo Gambit' },
  { moves: ['f4', 'e5', 'fxe5', 'd6', 'exd6', 'Nf6'], name: 'Bird Opening: From\'s Gambit, Langheld Gambit' },
  { moves: ['f4', 'd5', 'Nf3', 'Nf6', 'e3', 'c5'], name: 'Bird Opening: Lasker Variation' },
  { moves: ['e4', 'e5', 'Bc4', 'b5', 'Bxb5', 'c6'], name: 'Bishop\'s Opening: Anderssen Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Nf6', 'Nc3', 'b5'], name: 'Bishop\'s Opening: Horwitz Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'c3', 'd5'], name: 'Bishop\'s Opening: Lewis Countergambit' },
  { moves: ['e4', 'e5', 'Bc4', 'b5', 'Bxb5', 'f5'], name: 'Bishop\'s Opening: Thorold Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'c3', 'Qg5'], name: 'Bishop\'s Opening: del Rio Variation' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'e5'], name: 'Blackmar-Diemer Gambit: Lemberger Countergambit' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'f5'], name: 'Blackmar-Diemer Gambit: Netherlands Variation' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'c5'], name: 'Blackmar-Diemer Gambit: Reversed Albin Countergambit' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Nc3', 'Bf5'], name: 'Blackmar-Diemer Gambit: Zeller Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'Bb4+'], name: 'Bogo-Indian Defense' },
  { moves: ['e4', 'g5', 'd4', 'h6', 'h4', 'g4'], name: 'Borg Defense: Troon Gambit' },
  { moves: ['e4', 'c6', 'c4', 'd5', 'exd5', 'Qxd5'], name: 'Caro-Kann Defense: Accelerated Panov Attack, Pseudo-Scandinavian' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'e5', 'c5'], name: 'Caro-Kann Defense: Advance Variation, Botvinnik-Carls Defense' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'Nf6'], name: 'Caro-Kann Defense: Campomanes Attack' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nd2', 'Qb6'], name: 'Caro-Kann Defense: Edinburgh Variation' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'b5'], name: 'Caro-Kann Defense: Gurgenidze Counterattack' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'g6'], name: 'Caro-Kann Defense: Gurgenidze System' },
  { moves: ['e4', 'c6', 'Nc3', 'd5', 'Nf3', 'Bg4'], name: 'Caro-Kann Defense: Two Knights Attack, Mindeno Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'e5'], name: 'Catalan Opening: Hungarian Gambit' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'Qxd4', 'Nc6'], name: 'Center Game: Normal Variation' },
  { moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'c6'], name: 'Czech Defense' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'c3', 'dxc3'], name: 'Danish Gambit Accepted' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'c3', 'Ne7'], name: 'Danish Gambit Accepted: Svenonius Defense' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'c3', 'd5'], name: 'Danish Gambit Declined: Sörensen Defense' },
  { moves: ['d4', 'f5', 'c4', 'g6', 'Nc3', 'Nh6'], name: 'Dutch Defense: Bladel Variation' },
  { moves: ['d4', 'f5', 'c4', 'Nf6', 'g3', 'g6'], name: 'Dutch Defense: Leningrad Variation' },
  { moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6'], name: 'Dutch Defense: Semi-Leningrad Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'd5', 'exd5', 'Bd6'], name: 'Elephant Gambit: Maróczy Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'd5', 'exd5', 'e4'], name: 'Elephant Gambit: Paulsen Countergambit' },
  { moves: ['d4', 'b6', 'c4', 'Bb7', 'Nc3', 'e5'], name: 'English Defense: Eastbourne Gambit' },
  { moves: ['c4', 'e6', 'Nf3', 'd5', 'g3', 'c5'], name: 'English Opening: Agincourt Defense, Catalan Defense' },
  { moves: ['c4', 'e6', 'Nf3', 'd5', 'g3', 'c6'], name: 'English Opening: Agincourt Defense, Kurajica Defense' },
  { moves: ['c4', 'Nf6', 'Nf3', 'g6', 'g3', 'd5'], name: 'English Opening: Anglo-Indian Defense, Grünfeld Formation' },
  { moves: ['c4', 'Nf6', 'Nc3', 'e6', 'Nf3', 'Bb4'], name: 'English Opening: Anglo-Indian Defense, Nimzo-English' },
  { moves: ['c4', 'e6', 'Nf3', 'Nf6', 'g3', 'a6'], name: 'English Opening: Anglo-Indian Defense, Romanishin Variation' },
  { moves: ['c4', 'Nf6', 'Nf3', 'd5', 'cxd5', 'Nxd5'], name: 'English Opening: Anglo-Indian Defense, Scandinavian Defense, Exchange Variation' },
  { moves: ['c4', 'Nf6', 'Nf3', 'g6', 'g3', 'c6'], name: 'English Opening: Anglo-Indian Defense, Slav Formation' },
  { moves: ['c4', 'd5', 'cxd5', 'Qxd5', 'Nc3', 'Qa5'], name: 'English Opening: Anglo-Scandinavian Defense, Malvinas Variation' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'Nf3', 'Nc6'], name: 'English Opening: King\'s English Variation, Four Knights Variation' },
  { moves: ['c4', 'e5', 'Nc3', 'd6', 'g3', 'c6'], name: 'English Opening: King\'s English Variation, Keres Defense' },
  { moves: ['c4', 'e5', 'Nc3', 'd6', 'Nf3', 'Bg4'], name: 'English Opening: King\'s English Variation, Smyslov Defense' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'g6'], name: 'English Opening: King\'s English Variation, Two Knights Variation, Fianchetto Line' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'c6'], name: 'English Opening: King\'s English Variation, Two Knights Variation, Keres Variation' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'd5'], name: 'English Opening: King\'s English Variation, Two Knights Variation, Reversed Dragon' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'Bb4'], name: 'English Opening: King\'s English Variation, Two Knights Variation, Smyslov System' },
  { moves: ['c4', 'e6', 'Nc3', 'Nf6', 'e4', 'c5'], name: 'English Opening: Mikenas-Carls, Sicilian' },
  { moves: ['c4', 'e6', 'Nf3', 'd5', 'g3', 'Nf6'], name: 'English Opening: Neo-Catalan' },
  { moves: ['c4', 'Nf6', 'Nf3', 'c5', 'Nc3', 'Nc6'], name: 'English Opening: Symmetrical Variation, Four Knights Variation' },
  { moves: ['d4', 'e5', 'd5', 'Bc5', 'e4', 'Qh4'], name: 'Englund Gambit Declined: Diemer Counterattack' },
  { moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Bc5'], name: 'Englund Gambit: Felbecker Gambit' },
  { moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Qe7'], name: 'Englund Gambit: Main Line' },
  { moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'f6'], name: 'Englund Gambit: Soller Gambit Deferred' },
  { moves: ['d4', 'e5', 'dxe5', 'Nc6', 'Nf3', 'Nge7'], name: 'Englund Gambit: Zilbermints Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'Nf6'], name: 'Four Knights Game' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'e5', 'Bd7'], name: 'French Defense: Advance Variation, Extended Bishop Swap' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6'], name: 'French Defense: Classical Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'c4', 'dxe4'], name: 'French Defense: Diemer-Duhm Gambit Accepted' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nc6'], name: 'French Defense: Hecht-Reefschläger Variation' },
  { moves: ['e4', 'e6', 'f4', 'd5', 'Nf3', 'dxe4'], name: 'French Defense: La Bourdonnais Variation, Reuter Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'c5'], name: 'French Defense: Marshall Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'dxe4'], name: 'French Defense: Rubinstein Variation' },
  { moves: ['e4', 'e6', 'd4', 'a6', 'c4', 'b5'], name: 'French Defense: St. George Defense, Sanky-George Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nf6'], name: 'French Defense: Tarrasch Variation, Closed Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nc6'], name: 'French Defense: Tarrasch Variation, Guimard Defense' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'f5'], name: 'French Defense: Tarrasch Variation, Haberditz Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'a6'], name: 'French Defense: Tarrasch Variation, Modern System' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'Be7'], name: 'French Defense: Tarrasch Variation, Morozevich Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'c5'], name: 'French Defense: Tarrasch Variation, Open System' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4'], name: 'French Defense: Winawer Variation' },
  { moves: ['g4', 'd5', 'h3', 'e5', 'Bg2', 'c6'], name: 'Grob Opening: Keene Defense' },
  { moves: ['g4', 'd5', 'Bg2', 'Bxg4', 'c4', 'd4'], name: 'Grob Opening: Romford Countergambit' },
  { moves: ['g4', 'd5', 'e4', 'dxe4', 'Nc3', 'h5'], name: 'Grob Opening: Zilbermints Gambit, Schiller Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5'], name: 'Grünfeld Defense' },
  { moves: ['g3', 'f5', 'e4', 'fxe4', 'Qh5+', 'g6'], name: 'Hungarian Opening: Pachman Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'd5', 'b5'], name: 'Indian Defense: Anti-Grünfeld, Adorjan Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'f3', 'e5'], name: 'Indian Defense: Anti-Grünfeld, Alekhine Variation, Leko Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'e5', 'dxe5', 'Ne4'], name: 'Indian Defense: Budapest Defense, Fajarowicz Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'a6'], name: 'Indian Defense: Dzindzi-Indian Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'Ne4'], name: 'Indian Defense: Döry Indian' },
  { moves: ['d4', 'Nf6', 'Nf3', 'c5', 'd5', 'b5'], name: 'Indian Defense: Pseudo-Benko' },
  { moves: ['d4', 'Nf6', 'Nf3', 'b6', 'c3', 'e5'], name: 'Indian Defense: Schnepper Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'h6'], name: 'Italian Game: Anti-Fried Liver Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nd4'], name: 'Italian Game: Blackburne-Kostić Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5'], name: 'Italian Game: Giuoco Piano' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Be7'], name: 'Italian Game: Hungarian Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'd6'], name: 'Italian Game: Paris Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'f5'], name: 'Italian Game: Rousseau Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'], name: 'Italian Game: Two Knights Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'h6'], name: 'King\'s Gambit Accepted: Becker Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'g5'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Anderssen Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'd5'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Bledow Variation' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'Nf6'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Cozio Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'f5'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Gianutio Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'b5'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Kieseritzky Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'c6'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Lopez Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'Nc6'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Maurian Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4', 'Ne7'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit, Steinitz Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Ne7'], name: 'King\'s Gambit Accepted: Bonsch-Osmolovsky Variation' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7'], name: 'King\'s Gambit Accepted: Cunningham Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'd6'], name: 'King\'s Gambit Accepted: Fischer Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'f5'], name: 'King\'s Gambit Accepted: Gianutio Countergambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Nc6'], name: 'King\'s Gambit Accepted: MacLeod Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'd5'], name: 'King\'s Gambit Accepted: Modern Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Nf6'], name: 'King\'s Gambit Accepted: Schallopp Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'h5'], name: 'King\'s Gambit Accepted: Wagenbach Defense' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'exd5', 'Bc5'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Miles Gambit' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'exd5', 'exf4'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Modern Transfer' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'exd5', 'c6'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Nimzowitsch-Marshall Countergambit' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'exd5', 'e4'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Staunton Line' },
  { moves: ['e4', 'e5', 'f4', 'Qh4+', 'g3', 'Qe7'], name: 'King\'s Gambit Declined: Keene Defense' },
  { moves: ['e4', 'e5', 'f4', 'Nc6', 'Nf3', 'f5'], name: 'King\'s Gambit Declined: Miles Defense' },
  { moves: ['e4', 'e5', 'f4', 'f5', 'exf5', 'Qh4+'], name: 'King\'s Gambit Declined: Panteldakis Countergambit, Greco Variation' },
  { moves: ['e4', 'e5', 'f4', 'f5', 'exf5', 'Bc5'], name: 'King\'s Gambit Declined: Panteldakis Countergambit, Schiller\'s Defense' },
  { moves: ['e4', 'e5', 'f4', 'Bc5', 'Nf3', 'g5'], name: 'King\'s Gambit Declined: Senechaud Countergambit' },
  { moves: ['e4', 'e5', 'f4', 'f6', 'fxe5', 'Nc6'], name: 'King\'s Gambit Declined: Soller-Zilbermints Gambit' },
  { moves: ['e4', 'e5', 'f4', 'Nc6', 'Nf3', 'g5'], name: 'King\'s Gambit Declined: Zilbermints Double Gambit' },
  { moves: ['Nf3', 'Nf6', 'g3', 'd5', 'Bg2', 'e6'], name: 'King\'s Indian Attack, with e6' },
  { moves: ['Nf3', 'd5', 'g3', 'c5', 'Bg2', 'Nc6'], name: 'King\'s Indian Attack: French Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Bc5', 'Nxe5', 'Nc6'], name: 'King\'s Pawn Game: Busch-Gass Gambit, Chiodini Gambit' },
  { moves: ['e4', 'e5', 'd3', 'Nf6', 'f4', 'Bc5'], name: 'King\'s Pawn Game: Clam Variation, Radisch Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Qe7', 'Bc4', 'f5'], name: 'King\'s Pawn Game: Gunderam Defense, Gunderam Gambit' },
  { moves: ['e4', 'e5', 'c3', 'd5', 'Qh5', 'Bd6'], name: 'King\'s Pawn Game: MacLeod Attack, Norwalde Gambit' },
  { moves: ['e4', 'e5', 'd4', 'd6', 'dxe5', 'Bd7'], name: 'King\'s Pawn Game: Philidor Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Nxe5', 'Nc6'], name: 'Latvian Gambit: Fraser Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Nxe5', 'Qe7'], name: 'Latvian Gambit: Greco Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Bc4', 'Nf6'], name: 'Latvian Gambit: Mayet Attack, Morgado Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Bc4', 'b5'], name: 'Latvian Gambit: Mayet Attack, Strautins Gambit' },
  { moves: ['d4', 'Nc6', 'c4', 'e5', 'd5', 'Nd4'], name: 'Mikenas Defense: Cannstatter Variation' },
  { moves: ['d4', 'Nc6', 'c4', 'e5', 'd5', 'Nce7'], name: 'Mikenas Defense: Lithuanian Variation' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Bc4', 'b5'], name: 'Modern Defense: Bishop Attack, Bücker Gambit' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'd5'], name: 'Modern Defense: Lizard Defense, Mittenberger Gambit' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'c5'], name: 'Modern Defense: Modern Pterodactyl' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'b6'], name: 'Modern Defense: Mongredien Defense, with Nc3' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nf3', 'b6'], name: 'Modern Defense: Mongredien Defense, with Nf3' },
  { moves: ['d4', 'g6', 'c4', 'Bg7', 'e4', 'e5'], name: 'Modern Defense: Neo-Modern Defense' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'd6'], name: 'Modern Defense: Standard Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'f3', 'd5'], name: 'Neo-Grünfeld Defense: Goglidze Attack' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'd5'], name: 'Neo-Grünfeld Defense: with Nf3' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'g3', 'd5'], name: 'Neo-Grünfeld Defense: with g3' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4'], name: 'Nimzo-Indian Defense' },
  { moves: ['e4', 'Nc6', 'Nc3', 'Nf6', 'd4', 'e5'], name: 'Nimzowitsch Defense: Breyer Variation' },
  { moves: ['e4', 'Nc6', 'Nf3', 'Nf6', 'e5', 'Ng4'], name: 'Nimzowitsch Defense: El Columpio Defense' },
  { moves: ['e4', 'Nc6', 'd4', 'e5', 'dxe5', 'Bc5'], name: 'Nimzowitsch Defense: Kennedy Variation, Bielefelder Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'e5', 'dxe5', 'f6'], name: 'Nimzowitsch Defense: Kennedy Variation, Hammer Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'e5', 'dxe5', 'Qh4'], name: 'Nimzowitsch Defense: Kennedy Variation, Herford Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'e5', 'dxe5', 'd6'], name: 'Nimzowitsch Defense: Kennedy Variation, de Smet Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'exd5', 'Nb4'], name: 'Nimzowitsch Defense: Scandinavian Variation, Aachen Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Nc3', 'a6'], name: 'Nimzowitsch Defense: Scandinavian Variation, Bogoljubow Variation, Brandics Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Nc3', 'g6'], name: 'Nimzowitsch Defense: Scandinavian Variation, Bogoljubow Variation, Erben Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Nc3', 'e5'], name: 'Nimzowitsch Defense: Scandinavian Variation, Bogoljubow Variation, Heinola-Deppe Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Nc3', 'Nf6'], name: 'Nimzowitsch Defense: Scandinavian Variation, Bogoljubow Variation, Vehre Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'exd5', 'Qxd5'], name: 'Nimzowitsch Defense: Scandinavian Variation, Exchange Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'Nc3', 'c6'], name: 'Old Indian Defense: Czech Variation, with Nc3' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'Nf3', 'c6'], name: 'Old Indian Defense: Czech Variation, with Nf3' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'Nc3', 'Bf5'], name: 'Old Indian Defense: Janowski Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'Nf3', 'Bg4'], name: 'Old Indian Defense: Tartakower-Indian' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'Nc3', 'e5'], name: 'Old Indian Defense: Ukrainian Variation' },
  { moves: ['e4', 'b6', 'd4', 'c5', 'dxc5', 'Nc6'], name: 'Owen Defense: Hekili-Loa Gambit' },
  { moves: ['e4', 'f6', 'd4', 'b6', 'c4', 'Bb7'], name: 'Owen Defense: Unicorn Variation' },
  { moves: ['e4', 'b6', 'd4', 'Bb7', 'f3', 'e5'], name: 'Owen Defense: Wind Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nxe4'], name: 'Petrov\'s Defense: Damiano Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'd4', 'd5'], name: 'Petrov\'s Defense: Modern Attack, Symmetrical Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'Nc6'], name: 'Petrov\'s Defense: Stafford Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'exd4'], name: 'Philidor Defense: Exchange Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Nd7'], name: 'Philidor Defense: Hanham Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'Bc4', 'f5'], name: 'Philidor Defense: Lopez Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Nf6'], name: 'Philidor Defense: Nimzowitsch Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'f5'], name: 'Philidor Defense: Philidor Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'd6', 'd4', 'Bd7'], name: 'Philidor Defense: Philidor Gambit' },
  { moves: ['b4', 'e6', 'Bb2', 'Nf6', 'b5', 'b6'], name: 'Polish Opening: Queen\'s Indian Variation' },
  { moves: ['b4', 'e6', 'Bb2', 'Nf6', 'b5', 'a6'], name: 'Polish Opening: Queenside Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3', 'Nf6'], name: 'Ponziani Opening: Jaenisch Counterattack' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3', 'f5'], name: 'Ponziani Opening: Ponziani Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3', 'Be7'], name: 'Ponziani Opening: Romanishin Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3', 'Nge7'], name: 'Ponziani Opening: Réti Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'a6'], name: 'Queen\'s Gambit Accepted: Alekhine Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'Nf6'], name: 'Queen\'s Gambit Accepted: Central Variation, Alekhine System' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'b5'], name: 'Queen\'s Gambit Accepted: Central Variation, Greco Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'e5'], name: 'Queen\'s Gambit Accepted: Central Variation, McDonnell Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'Nc6'], name: 'Queen\'s Gambit Accepted: Central Variation, Modern Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'c5'], name: 'Queen\'s Gambit Accepted: Central Variation, Rubinstein Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'Nd7'], name: 'Queen\'s Gambit Accepted: Godes Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'c5'], name: 'Queen\'s Gambit Accepted: Gunsberg Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'e6'], name: 'Queen\'s Gambit Accepted: Rosenthal Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4', 'f5'], name: 'Queen\'s Gambit Accepted: Schwartz Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'b5'], name: 'Queen\'s Gambit Accepted: Slav Gambit' },
  { moves: ['d4', 'e6', 'c4', 'b6', 'Nc3', 'd5'], name: 'Queen\'s Gambit Declined: Alapin Variation' },
  { moves: ['d4', 'd5', 'c4', 'c5', 'dxc5', 'd4'], name: 'Queen\'s Gambit Declined: Austrian Attack, Salvio Countergambit' },
  { moves: ['d4', 'd5', 'c4', 'c5', 'cxd5', 'Nf6'], name: 'Queen\'s Gambit Declined: Austrian Defense, Gusev Countergambit' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Be7'], name: 'Queen\'s Gambit Declined: Charousek Variation' },
  { moves: ['d4', 'd5', 'c4', 'Nc6', 'cxd5', 'Qxd5'], name: 'Queen\'s Gambit Declined: Chigorin Defense, Exchange Variation' },
  { moves: ['d4', 'd5', 'c4', 'Nc6', 'Nf3', 'e5'], name: 'Queen\'s Gambit Declined: Chigorin Defense, Lazard Gambit' },
  { moves: ['d4', 'd5', 'c4', 'Nc6', 'Nf3', 'Bg4'], name: 'Queen\'s Gambit Declined: Chigorin Defense, Main Line' },
  { moves: ['d4', 'd5', 'c4', 'Nc6', 'Nc3', 'e5'], name: 'Queen\'s Gambit Declined: Chigorin Defense, Tartakower Gambit' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'a6'], name: 'Queen\'s Gambit Declined: Janowski Variation' },
  { moves: ['d4', 'd5', 'c4', 'Nf6', 'cxd5', 'c6'], name: 'Queen\'s Gambit Declined: Marshall Defense, Tan Gambit' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6'], name: 'Queen\'s Gambit Declined: Normal Defense' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nf3', 'c5'], name: 'Queen\'s Gambit Declined: Tarrasch Defense, Pseudo-Tarrasch' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6'], name: 'Queen\'s Indian Defense' },
  { moves: ['d4', 'd5', 'Bf4', 'c5', 'e4', 'dxe4'], name: 'Queen\'s Pawn Game: Accelerated London System, Steinitz Countergambit, Morris Countergambit Accepted' },
  { moves: ['d4', 'g6', 'Nf3', 'Bg7', 'Nc3', 'd5'], name: 'Queen\'s Pawn Game: Chigorin Variation, Fianchetto Defense' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'e3', 'Bf5'], name: 'Queen\'s Pawn Game: Colle System, Anti-Colle' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bg5', 'Ne4'], name: 'Queen\'s Pawn Game: Torre Attack, Gossip Variation' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bg5', 'g6'], name: 'Queen\'s Pawn Game: Torre Attack, Grünfeld Variation' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'c4', 'b5'], name: 'Queen\'s Pawn Game: Zilbermints Countergambit' },
  { moves: ['e4', 'g6', 'd4', 'd6', 'Nc3', 'c6'], name: 'Rat Defense: Accelerated Gurgenidze' },
  { moves: ['d4', 'd6', 'c4', 'e5', 'dxe5', 'Nc6'], name: 'Rat Defense: English Rat, Lisbon Gambit' },
  { moves: ['d4', 'd6', 'c4', 'e5', 'dxe5', 'Be6'], name: 'Rat Defense: English Rat, Pounds Gambit' },
  { moves: ['e4', 'd6', 'f4', 'd5', 'exd5', 'Nf6'], name: 'Rat Defense: Fuller Gambit' },
  { moves: ['d4', 'Nf6', 'Nc3', 'd5', 'Bg5', 'Ne4'], name: 'Richter-Veresov Attack: Boyce Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Bb4'], name: 'Ruy Lopez: Alapin Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6'], name: 'Ruy Lopez: Berlin Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nd4'], name: 'Ruy Lopez: Bird Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'g5'], name: 'Ruy Lopez: Brentano Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a5'], name: 'Ruy Lopez: Bulgarian Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Bc5'], name: 'Ruy Lopez: Classical Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nge7'], name: 'Ruy Lopez: Cozio Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'g6'], name: 'Ruy Lopez: Fianchetto Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Be7'], name: 'Ruy Lopez: Lucena Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6'], name: 'Ruy Lopez: Morphy Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'f6'], name: 'Ruy Lopez: Nürnberg Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Na5'], name: 'Ruy Lopez: Pollock Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nb8'], name: 'Ruy Lopez: Retreat Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'b6'], name: 'Ruy Lopez: Rotary-Albany Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'f5'], name: 'Ruy Lopez: Schliemann Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'd5'], name: 'Ruy Lopez: Spanish Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'd6'], name: 'Ruy Lopez: Steinitz Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Qe7'], name: 'Ruy Lopez: Vinogradov Variation' },
  { moves: ['Nf3', 'd5', 'c4', 'd4', 'b4', 'c5'], name: 'Réti Opening: Advance Variation, Michel Gambit' },
  { moves: ['Nf3', 'd5', 'c4', 'd4', 'b4', 'g5'], name: 'Réti Opening: Advance Variation, Navara Gambit' },
  { moves: ['Nf3', 'd5', 'c4', 'dxc4', 'e3', 'Be6'], name: 'Réti Opening: Réti Gambit, Keres Variation' },
  { moves: ['e4', 'd5', 'exd5', 'c6', 'dxc6', 'Nxc6'], name: 'Scandinavian Defense: Blackburne Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'e5', 'dxe6', 'Bxe6'], name: 'Scandinavian Defense: Boehnke Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qd6'], name: 'Scandinavian Defense: Gubinsky-Melts Defense' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6', 'c4', 'e6'], name: 'Scandinavian Defense: Icelandic-Palme Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'c6', 'dxc6', 'e5'], name: 'Scandinavian Defense: Kloosterboer Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5'], name: 'Scandinavian Defense: Main Line' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6', 'd4', 'Nxd5'], name: 'Scandinavian Defense: Marshall Variation' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6', 'c4', 'c6'], name: 'Scandinavian Defense: Panov Transfer' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6', 'd4', 'Bg4'], name: 'Scandinavian Defense: Portuguese Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6', 'd4', 'g6'], name: 'Scandinavian Defense: Richter Variation' },
  { moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qd8'], name: 'Scandinavian Defense: Valencian Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'Nxd4'], name: 'Scotch Game: Lolli Variation' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'c6'], name: 'Semi-Slav Defense: Accelerated Move Order' },
  { moves: ['e4', 'c5', 'Nf3', 'g6', 'c4', 'Bh6'], name: 'Sicilian Defense: Acton Extension' },
  { moves: ['e4', 'c5', 'c3', 'd5', 'exd5', 'Nf6'], name: 'Sicilian Defense: Alapin Variation, Anti-Alapin Gambit' },
  { moves: ['e4', 'c5', 'c3', 'd5', 'exd5', 'Qxd5'], name: 'Sicilian Defense: Alapin Variation, Barmen Defense' },
  { moves: ['e4', 'c5', 'Nc3', 'e6', 'g3', 'd5'], name: 'Sicilian Defense: Closed, Korchnoi Defense' },
  { moves: ['e4', 'c5', 'Nf3', 'f5', 'exf5', 'Nh6'], name: 'Sicilian Defense: Double-Dutch Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'a6'], name: 'Sicilian Defense: Drazic Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'e6'], name: 'Sicilian Defense: Franco-Sicilian Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'g6', 'd4', 'f5'], name: 'Sicilian Defense: Frederico Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4'], name: 'Sicilian Defense: French Variation, Open' },
  { moves: ['e4', 'c5', 'Nf3', 'g6', 'd4', 'Bg7'], name: 'Sicilian Defense: Hyperaccelerated Pterodactyl' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'g3', 'b5'], name: 'Sicilian Defense: Kotov Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'd4', 'd5'], name: 'Sicilian Defense: Marshall Counterattack' },
  { moves: ['e4', 'c5', 'f4', 'd5', 'exd5', 'Nf6'], name: 'Sicilian Defense: McDonnell Attack, Tal Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'Nf6'], name: 'Sicilian Defense: Modern Variations, Anti-Qxd4 Move Order' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'Bb5+', 'Bd7'], name: 'Sicilian Defense: Moscow Variation, Main Line' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'Bb5', 'Nb8'], name: 'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack, Brooklyn Retreat Defense' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'Bb5', 'g6'], name: 'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack, Fianchetto Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c4', 'e6'], name: 'Sicilian Defense: O\'Kelly Variation, Maróczy Bind, Paulsen Line' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c4', 'd6'], name: 'Sicilian Defense: O\'Kelly Variation, Maróczy Bind, Robatsch Line' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c3', 'Nf6'], name: 'Sicilian Defense: O\'Kelly Variation, Venice System, Barcza Line' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c3', 'b5'], name: 'Sicilian Defense: O\'Kelly Variation, Venice System, Ljubojevic Line' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c3', 'd6'], name: 'Sicilian Defense: O\'Kelly Variation, Venice System, Steiner Line' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'dxc3'], name: 'Sicilian Defense: Smith-Morra Gambit Accepted' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'Nf6'], name: 'Sicilian Defense: Smith-Morra Gambit Declined, Alapin Formation' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'e5'], name: 'Sicilian Defense: Smith-Morra Gambit Declined, Center Formation' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'd3'], name: 'Sicilian Defense: Smith-Morra Gambit Declined, Push Variation' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'd5'], name: 'Sicilian Defense: Smith-Morra Gambit Declined, Scandinavian Formation' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'c3', 'Qa5'], name: 'Sicilian Defense: Smith-Morra Gambit Declined, Wing Formation' },
  { moves: ['e4', 'c5', 'b4', 'cxb4', 'a3', 'bxa3'], name: 'Sicilian Defense: Wing Gambit, Carlsbad Variation' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nc3', 'e5'], name: 'Slav Defense: Winawer Countergambit' },
  { moves: ['d4', 'c6', 'Nf3', 'Nf6', 'c4', 'b5'], name: 'Slav Indian: Kudischewitsch Gambit' },
  { moves: ['Na3', 'e5', 'Nc4', 'Nc6', 'e4', 'f5'], name: 'Sodium Attack: Durkin Gambit' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'c5'], name: 'Tarrasch Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'g6'], name: 'Three Knights Opening: Steinitz Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3', 'f5'], name: 'Three Knights Opening: Winawer Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'e6', 'Bg5', 'h6'], name: 'Torre Attack: Classical Defense, Nimzowitsch Variation' },
  { moves: ['d4', 'Nf6', 'Bg5', 'Ne4', 'Bf4', 'g5'], name: 'Trompowsky Attack: Borg Variation' },
  { moves: ['e4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'e5'], name: 'Van Geet Opening: Grünfeld Defense' },
  { moves: ['Nc3', 'd6', 'f4', 'e5', 'fxe5', 'Nc6'], name: 'Van Geet Opening: Hergert Gambit' },
  { moves: ['Nc3', 'e5', 'e3', 'd5', 'Qh5', 'Be6'], name: 'Van Geet Opening: Hulsemann Gambit' },
  { moves: ['Nc3', 'e5', 'e3', 'd5', 'Qh5', 'Nf6'], name: 'Van Geet Opening: Liebig Gambit' },
  { moves: ['Nc3', 'd5', 'f4', 'd4', 'Ne4', 'c5'], name: 'Van Geet Opening: Melleby Gambit' },
  { moves: ['Nc3', 'd5', 'f4', 'd4', 'Ne4', 'e5'], name: 'Van Geet Opening: Pfeiffer Gambit' },
  { moves: ['Nc3', 'd5', 'e3', 'e5', 'd4', 'Bb4'], name: 'Van Geet Opening: Sleipnir Gambit' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4', 'Nxe4'], name: 'Vienna Game: Frankenstein-Dracula Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6', 'd4', 'f5'], name: 'Vienna Game: Philidor Countergambit' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4', 'Bb4'], name: 'Vienna Game: Stanley Variation, Reversed Spanish' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6', 'Bc4', 'Nf6'], name: 'Vienna Game: Stanley Variation, Three Knights Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5'], name: 'Vienna Game: Vienna Gambit, Main Line' },
  { moves: ['e4', 'e5', 'Nc3', 'Bb4', 'Qg4', 'Nf6'], name: 'Vienna Game: Zhuravlev Countergambit' },
  { moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'Ne4'], name: 'Vulture Defense' },
  { moves: ['a4', 'b6', 'd4', 'd5', 'Nc3', 'Nd7'], name: 'Ware Opening: Cologne Gambit' },
  { moves: ['Nf3', 'f6', 'e4', 'Nh6', 'd4', 'Nf7'], name: 'Zukertort Opening: Arctic Defense, Drunken Knight Variation' },
  { moves: ['Nf3', 'e5', 'Nxe5', 'Nc6', 'Nxc6', 'dxc6'], name: 'Zukertort Opening: The Walrus' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'Na3'], name: 'Alekhine Defense: Buckley Attack' },
  { moves: ['e4', 'Nf6', 'Bc4', 'Nxe4', 'Bxf7+'], name: 'Alekhine Defense: Krejcik Variation, Krejcik Gambit' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'Nc3'], name: 'Alekhine Defense: Sämisch Attack' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'c4'], name: 'Alekhine Defense: Two Pawns Attack' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5', 'b3'], name: 'Alekhine Defense: Welling Variation' },
  { moves: ['Nh3', 'd5', 'g3', 'e5', 'f4'], name: 'Amar Opening: Paris Gambit' },
  { moves: ['d4', 'Nf6', 'Nc3', 'd5', 'Qd3'], name: 'Amazon Attack: Siberian Attack' },
  { moves: ['f3', 'f5', 'e4', 'fxe4', 'Nc3'], name: 'Barnes Opening: Gedult Gambit' },
  { moves: ['f3', 'e5', 'e4', 'Nf6', 'Bc4'], name: 'Barnes Opening: Walkerling' },
  { moves: ['d4', 'c5', 'd5', 'Nf6', 'Nf3'], name: 'Benoni Defense: Benoni-Indian Defense, Kingside Move Order' },
  { moves: ['d4', 'c5', 'd5', 'f5', 'e4'], name: 'Benoni Defense: Benoni-Staunton Gambit' },
  { moves: ['e4', 'e6', 'd4', 'c5', 'd5'], name: 'Benoni Defense: French Benoni' },
  { moves: ['f4', 'Nf6', 'Nf3', 'g6', 'b4'], name: 'Bird Opening: Batavo-Polish Attack' },
  { moves: ['e4', 'e5', 'Bc4', 'Nf6', 'f4'], name: 'Bishop\'s Opening: Berlin Defense, Greco Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'f5', 'd3'], name: 'Bishop\'s Opening: Calabrese Countergambit, Jaenisch Variation' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'd4'], name: 'Bishop\'s Opening: Lewis Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'Qe2'], name: 'Bishop\'s Opening: Lopez Variation' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'b4'], name: 'Bishop\'s Opening: McDonnell Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'c3'], name: 'Bishop\'s Opening: Philidor Variation' },
  { moves: ['e4', 'e5', 'Bc4', 'Nf6', 'd4'], name: 'Bishop\'s Opening: Ponziani Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5', 'f4'], name: 'Bishop\'s Opening: Stein Gambit' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'f3'], name: 'Blackmar-Diemer Gambit: Blackmar Gambit' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Be3'], name: 'Blackmar-Diemer Gambit: Diemer-Rosenberg Attack' },
  { moves: ['d4', 'd5', 'e4', 'dxe4', 'Bc4'], name: 'Blackmar-Diemer Gambit: Fritz Attack' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'e5'], name: 'Caro-Kann Defense: Advance Variation' },
  { moves: ['e4', 'c6', 'Nf3', 'd5', 'd3'], name: 'Caro-Kann Defense: Endgame Offer' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'exd5'], name: 'Caro-Kann Defense: Exchange Variation' },
  { moves: ['e4', 'c6', 'Nc3', 'd5', 'Qf3'], name: 'Caro-Kann Defense: Goldman Variation' },
  { moves: ['e4', 'c6', 'b4', 'd5', 'b5'], name: 'Caro-Kann Defense: Labahn Attack, Double Gambit' },
  { moves: ['e4', 'c6', 'b4', 'e5', 'Bb2'], name: 'Caro-Kann Defense: Labahn Attack, Polish Variation' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'f3'], name: 'Caro-Kann Defense: Maróczy Variation' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Be3'], name: 'Caro-Kann Defense: Mieses Gambit' },
  { moves: ['e4', 'c6', 'd4', 'd5', 'Nd2'], name: 'Caro-Kann Defense: Modern Variation' },
  { moves: ['e4', 'c6', 'Nc3', 'd5', 'h3'], name: 'Caro-Kann Defense: St. Patrick\'s Attack' },
  { moves: ['e4', 'c6', 'c4', 'd5', 'e5'], name: 'Caro-Kann Defense: Toikkanen Gambit' },
  { moves: ['e4', 'c6', 'Nc3', 'd5', 'Nf3'], name: 'Caro-Kann Defense: Two Knights Attack' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g3'], name: 'Catalan Opening' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'f4'], name: 'Center Game: Halasz-McDonnell Gambit' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'Nf3'], name: 'Center Game: Kieseritzky Variation' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'Bd3'], name: 'Center Game: Ross Gambit' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'Bc4'], name: 'Center Game: von der Lasa Gambit' },
  { moves: ['e4', 'e5', 'd4', 'exd4', 'c3'], name: 'Danish Gambit' },
  { moves: ['d4', 'f5', 'c4', 'e6', 'e4'], name: 'Dutch Defense: Bellon Gambit' },
  { moves: ['d4', 'f5', 'c4', 'Nf6', 'g3'], name: 'Dutch Defense: Fianchetto Variation' },
  { moves: ['d4', 'f5', 'h3', 'Nf6', 'g4'], name: 'Dutch Defense: Janzen-Korchnoi Gambit' },
  { moves: ['d4', 'f5', 'Nc3', 'd5', 'e4'], name: 'Dutch Defense: Kingfisher Gambit' },
  { moves: ['d4', 'f5', 'Qd3', 'e6', 'g4'], name: 'Dutch Defense: Manhattan Gambit, Anti-Classical Line' },
  { moves: ['d4', 'f5', 'Qd3', 'g6', 'g4'], name: 'Dutch Defense: Manhattan Gambit, Anti-Leningrad' },
  { moves: ['d4', 'f5', 'Qd3', 'd6', 'g4'], name: 'Dutch Defense: Manhattan Gambit, Anti-Modern' },
  { moves: ['d4', 'f5', 'Qd3', 'd5', 'g4'], name: 'Dutch Defense: Manhattan Gambit, Anti-Stonewall' },
  { moves: ['d4', 'f5', 'c4', 'Nf6', 'Nc3'], name: 'Dutch Defense: Queen\'s Knight Variation' },
  { moves: ['d4', 'f5', 'c4', 'e6', 'Nc3'], name: 'Dutch Defense: Rubinstein Variation' },
  { moves: ['d4', 'f5', 'Bf4', 'e6', 'g4'], name: 'Dutch Defense: Senechaud Gambit' },
  { moves: ['d4', 'f5', 'Nc3', 'Nf6', 'g4'], name: 'Dutch Defense: Spielmann Gambit' },
  { moves: ['d4', 'f5', 'e4', 'fxe4', 'Nd2'], name: 'Dutch Defense: Staunton Gambit, American Attack' },
  { moves: ['c4', 'f5', 'Nf3', 'd6', 'e4'], name: 'English Opening: Anglo-Dutch Variation, Chabanon Gambit' },
  { moves: ['c4', 'f5', 'Nc3', 'Nf6', 'e4'], name: 'English Opening: Anglo-Dutch Variation, Ferenc Gambit' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3'], name: 'English Opening: Carls-Bremen System' },
  { moves: ['c4', 'e5', 'Nc3', 'Nc6', 'Nf3'], name: 'English Opening: King\'s English Variation, Three Knights System' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6', 'f4'], name: 'English Opening: King\'s English, Mazedonisch' },
  { moves: ['c4', 'e6', 'Nc3', 'Nf6', 'e4'], name: 'English Opening: Mikenas-Carls Variation' },
  { moves: ['c4', 'Nf6', 'd4', 'c5', 'Nf3'], name: 'English Opening: Symmetrical Variation, Anti-Benoni Variation' },
  { moves: ['c4', 'Nf6', 'Nc3', 'c5', 'g3'], name: 'English Opening: Symmetrical Variation, Fianchetto Variation' },
  { moves: ['c4', 'c5', 'Nf3', 'Nf6', 'b4'], name: 'English Opening: Symmetrical Variation, Napolitano Gambit' },
  { moves: ['c4', 'c5', 'Nc3', 'Nf6', 'Nf3'], name: 'English Opening: Symmetrical Variation, Three Knights Variation' },
  { moves: ['c4', 'c5', 'Nc3', 'Nc6', 'g3'], name: 'English Opening: Symmetrical Variation, Two Knights, Fianchetto Variation' },
  { moves: ['d4', 'e5', 'Nf3', 'e4', 'Ng1'], name: 'Englund Gambit Declined: Reversed Brooklyn' },
  { moves: ['d4', 'e5', 'Nf3', 'e4', 'Ne5'], name: 'Englund Gambit Declined: Reversed Mokele Mbembe' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'e5'], name: 'French Defense: Advance Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Be3'], name: 'French Defense: Alapin Gambit' },
  { moves: ['e4', 'e6', 'b4', 'Bxb4', 'e5'], name: 'French Defense: Banzai-Leong Gambit, Pinova Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'c4'], name: 'French Defense: Diemer-Duhm Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'exd5'], name: 'French Defense: Exchange Variation' },
  { moves: ['e4', 'e6', 'd4', 'f5', 'exf5'], name: 'French Defense: Franco-Hiva Gambit Accepted' },
  { moves: ['e4', 'e6', 'b3', 'd5', 'Bb2'], name: 'French Defense: Horwitz Attack, Papa-Ticulat Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nh3'], name: 'French Defense: Morphy Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nc3'], name: 'French Defense: Paulsen Variation' },
  { moves: ['e4', 'e6', 'Nc3', 'd5', 'f4'], name: 'French Defense: Pelikan Variation' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nf3'], name: 'French Defense: Perseus Gambit' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Bd3'], name: 'French Defense: Schlechter Variation' },
  { moves: ['e4', 'e6', 'd4', 'a6', 'c4'], name: 'French Defense: St. George Defense, Three Pawn Attack' },
  { moves: ['e4', 'e6', 'd4', 'd5', 'Nd2'], name: 'French Defense: Tarrasch Variation' },
  { moves: ['e4', 'e6', 'Nf3', 'd5', 'Nc3'], name: 'French Defense: Two Knights Variation' },
  { moves: ['g4', 'd5', 'Bg2', 'h5', 'gxh5'], name: 'Grob Opening: Grob Gambit, Basman Gambit' },
  { moves: ['g4', 'd5', 'Bg2', 'Bxg4', 'c4'], name: 'Grob Opening: Grob Gambit, Fritz Gambit' },
  { moves: ['g4', 'd5', 'Bg2', 'c6', 'g5'], name: 'Grob Opening: Spike Attack' },
  { moves: ['g4', 'e5', 'Bg2', 'd5', 'c4'], name: 'Grob Opening: Spike, Hurst Attack' },
  { moves: ['g4', 'd5', 'e4', 'dxe4', 'Nc3'], name: 'Grob Opening: Zilbermints Gambit' },
  { moves: ['g3', 'd5', 'Bg2', 'e5', 'b4'], name: 'Hungarian Opening: Bücker Gambit' },
  { moves: ['g3', 'e5', 'Nf3', 'e4', 'Nh4'], name: 'Hungarian Opening: Reversed Norwegian Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'd5'], name: 'Indian Defense: Anti-Grünfeld, Advance Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'f3'], name: 'Indian Defense: Anti-Grünfeld, Alekhine Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'h4'], name: 'Indian Defense: Anti-Grünfeld, Basman-Williams Attack' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3'], name: 'Indian Defense: Anti-Nimzo-Indian' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'g4'], name: 'Indian Defense: Devin Gambit' },
  { moves: ['d4', 'Nf6', 'f3', 'd5', 'g4'], name: 'Indian Defense: Gedult Attack' },
  { moves: ['d4', 'Nf6', 'Nf3', 'e6', 'Bf4'], name: 'Indian Defense: London System' },
  { moves: ['d4', 'Nf6', 'f3', 'd5', 'e4'], name: 'Indian Defense: Paleface Attack, Blackmar-Diemer Gambit Deferred' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6', 'g3'], name: 'Indian Defense: Przepiorka Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'e6', 'Bg5'], name: 'Indian Defense: Seirawan Attack' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nxe5'], name: 'Irish Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4'], name: 'Italian Game' },
  { moves: ['d4', 'e6', 'c4', 'Bb4+', 'Nc3'], name: 'Kangaroo Defense: Keres Defense, Transpositional Variation' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Qe2'], name: 'King\'s Gambit Accepted: Basman Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bc4'], name: 'King\'s Gambit Accepted: Bishop\'s Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Qf3'], name: 'King\'s Gambit Accepted: Breyer Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Qh5'], name: 'King\'s Gambit Accepted: Carrera Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Qg4'], name: 'King\'s Gambit Accepted: Dodo Variation' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nh3'], name: 'King\'s Gambit Accepted: Eisenberg Variation' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'g3'], name: 'King\'s Gambit Accepted: Gaga Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3'], name: 'King\'s Gambit Accepted: King\'s Knight\'s Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Nc3'], name: 'King\'s Gambit Accepted: Mason-Keres Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'b3'], name: 'King\'s Gambit Accepted: Orsini Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Ne2'], name: 'King\'s Gambit Accepted: Paris Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bb5'], name: 'King\'s Gambit Accepted: Schurig Gambit, with Bb5' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Bd3'], name: 'King\'s Gambit Accepted: Schurig Gambit, with Bd3' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'h4'], name: 'King\'s Gambit Accepted: Stamma Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Be2'], name: 'King\'s Gambit Accepted: Tartakower Gambit' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'Kf2'], name: 'King\'s Gambit Accepted: Tumbleweed' },
  { moves: ['e4', 'e5', 'f4', 'exf4', 'd4'], name: 'King\'s Gambit Accepted: Villemson Gambit' },
  { moves: ['e4', 'e5', 'f4', 'Bc5', 'Qh5'], name: 'King\'s Gambit Declined: Classical Variation, Walthoffen Attack' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'exd5'], name: 'King\'s Gambit Declined: Falkbeer Countergambit Accepted' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'Nf3'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Blackburne Attack' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'd4'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Hinrichsen Gambit' },
  { moves: ['e4', 'e5', 'f4', 'd5', 'Nc3'], name: 'King\'s Gambit Declined: Falkbeer Countergambit, Milner-Barry Variation' },
  { moves: ['Nf3', 'Nf6', 'g3', 'g6', 'b4'], name: 'King\'s Indian Attack: Smyslov Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3'], name: 'King\'s Indian Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'g3'], name: 'King\'s Indian Defense: Fianchetto Variation, Immediate Fianchetto' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6', 'c4'], name: 'King\'s Indian Defense: Normal Variation, King\'s Knight Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'g3'], name: 'King\'s Knight Opening: Konstantinopolsky' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c4'], name: 'King\'s Pawn Game: Dresden Opening' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'b4'], name: 'King\'s Pawn Game: Pachman Wing Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Be2'], name: 'King\'s Pawn Game: Tayler Opening' },
  { moves: ['e4', 'e5', 'Qg4', 'Nf6', 'Qf5'], name: 'King\'s Pawn Opening: Speers' },
  { moves: ['h4', 'd5', 'd4', 'c5', 'e4'], name: 'Kádas Opening: Myers Variation' },
  { moves: ['h4', 'f5', 'e4', 'fxe4', 'd3'], name: 'Kádas Opening: Steinbok Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'exf5'], name: 'Latvian Gambit Accepted' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'c4'], name: 'Latvian Gambit: Diepstraten Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'g4'], name: 'Latvian Gambit: Lobster Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'd4'], name: 'Latvian Gambit: Mason Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Bc4'], name: 'Latvian Gambit: Mayet Attack' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'Nc3'], name: 'Latvian Gambit: Mlotkowski Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'f5', 'b4'], name: 'Latvian Gambit: Senechaud Gambit' },
  { moves: ['e4', 'd6', 'd4', 'Nf6', 'f3'], name: 'Lion Defense: Lion\'s Jaw' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6', 'Bf4'], name: 'London System' },
  { moves: ['d3', 'c5', 'Nc3', 'Nc6', 'g3'], name: 'Mieses Opening: Venezolana Variation' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Bc4'], name: 'Modern Defense: Bishop Attack' },
  { moves: ['d4', 'g6', 'h4', 'Nf6', 'h5'], name: 'Modern Defense: Lizard Defense, Pirc-Diemer Gambit' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3'], name: 'Modern Defense: Standard Line' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'f4'], name: 'Modern Defense: Three Pawns Attack' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Bd2'], name: 'Modern Defense: Westermann Gambit' },
  { moves: ['e4', 'g6', 'd4', 'Bg7', 'Bd3'], name: 'Modern Defense: Wind Gambit' },
  { moves: ['Nf3', 'd5', 'b3', 'c5', 'e4'], name: 'Nimzo-Larsen Attack: Norfolk Gambit' },
  { moves: ['b3', 'e5', 'Bb2', 'Nc6', 'f4'], name: 'Nimzo-Larsen Attack: Pachman Gambit' },
  { moves: ['b3', 'f5', 'Bb2', 'e6', 'e4'], name: 'Nimzo-Larsen Attack: Ringelbach Gambit' },
  { moves: ['b3', 'Nf6', 'Bb2', 'g6', 'g4'], name: 'Nimzo-Larsen Attack: Spike Variation' },
  { moves: ['e4', 'Nc6', 'Nf3', 'f5', 'exf5'], name: 'Nimzowitsch Defense: Colorado Countergambit Accepted' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Be3'], name: 'Nimzowitsch Defense: Hornung Gambit' },
  { moves: ['e4', 'Nc6', 'd4', 'e5', 'd5'], name: 'Nimzowitsch Defense: Kennedy Variation, Linksspringer Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'e5'], name: 'Nimzowitsch Defense: Scandinavian Variation, Advance Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'd5', 'Nc3'], name: 'Nimzowitsch Defense: Scandinavian Variation, Bogoljubow Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'd6', 'g4'], name: 'Old Indian Defense: Aged Gibbon Gambit' },
  { moves: ['e4', 'b6', 'd4', 'Bb7', 'Bg5'], name: 'Owen Defense: Naselwaus Gambit' },
  { moves: ['e4', 'b6', 'd4', 'Bb7', 'Nf3'], name: 'Owen Defense: Smith Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Bc4'], name: 'Petrov\'s Defense: Italian Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'd4'], name: 'Petrov\'s Defense: Modern Attack' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nc3'], name: 'Petrov\'s Defense: Three Knights Game' },
  { moves: ['e4', 'd6', 'd4', 'Nf6', 'Nf3'], name: 'Pirc Defense: Roscher Gambit' },
  { moves: ['d4', 'b5', 'e4', 'Bb7', 'Bxb5'], name: 'Polish Defense: Spassky Gambit Accepted' },
  { moves: ['b4', 'e5', 'Bb2', 'f6', 'b5'], name: 'Polish Opening: Bugayev Advance Variation' },
  { moves: ['b4', 'Nf6', 'Bb2', 'g6', 'e4'], name: 'Polish Opening: King\'s Indian Variation, Schiffler Attack' },
  { moves: ['b4', 'd5', 'Bb2', 'c6', 'a4'], name: 'Polish Opening: Myers Variation' },
  { moves: ['b4', 'e5', 'Bb2', 'f6', 'e4'], name: 'Polish Opening: Tartakower Gambit' },
  { moves: ['Nf3', 'Nf6', 'b4', 'g6', 'Bb2'], name: 'Polish Opening: Zukertort System' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'c3'], name: 'Ponziani Opening' },
  { moves: ['e4', 'e5', 'Bb5', 'Bc5', 'b4'], name: 'Portuguese Opening: Miguel Gambit' },
  { moves: ['e4', 'e5', 'Bb5', 'Nf6', 'd4'], name: 'Portuguese Opening: Portuguese Gambit' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Qa4+'], name: 'Queen\'s Gambit Accepted: Accelerated Mannheim Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'Nf3'], name: 'Queen\'s Gambit Accepted: Normal Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e3'], name: 'Queen\'s Gambit Accepted: Old Variation' },
  { moves: ['d4', 'd5', 'c4', 'dxc4', 'e4'], name: 'Queen\'s Gambit Accepted: Saduleto Variation' },
  { moves: ['d4', 'd5', 'c4', 'Bf5', 'Qb3'], name: 'Queen\'s Gambit Declined: Baltic Defense, Queen Attack' },
  { moves: ['d4', 'd5', 'c4', 'e6', 'Nc3'], name: 'Queen\'s Gambit Declined: Queen\'s Knight Variation' },
  { moves: ['d4', 'd5', 'Bf4', 'c5', 'dxc5'], name: 'Queen\'s Pawn Game: Accelerated London System, Steinitz Countergambit Accepted' },
  { moves: ['d4', 'd5', 'Bf4', 'c5', 'e4'], name: 'Queen\'s Pawn Game: Accelerated London System, Steinitz Countergambit, Morris Countergambit' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'e3'], name: 'Queen\'s Pawn Game: Colle System' },
  { moves: ['d4', 'Nf6', 'Nc3', 'd5', 'e4'], name: 'Queen\'s Pawn Game: Hübsch Gambit' },
  { moves: ['d4', 'c5', 'c4', 'cxd4', 'e3'], name: 'Queen\'s Pawn Game: Liedmann Gambit' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bf4'], name: 'Queen\'s Pawn Game: London System' },
  { moves: ['d4', 'd5', 'Nf3', 'e6', 'Bf4'], name: 'Queen\'s Pawn Game: London System, with e6' },
  { moves: ['d4', 'd5', 'e3', 'Nf6', 'Bd3'], name: 'Queen\'s Pawn Game: Stonewall Attack' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'g3'], name: 'Queen\'s Pawn Game: Symmetrical Variation, Pseudo-Catalan' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6', 'Bg5'], name: 'Queen\'s Pawn Game: Torre Attack' },
  { moves: ['d4', 'Nf6', 'f3', 'd5', 'Nc3'], name: 'Queen\'s Pawn Game: Veresov, Richter Attack' },
  { moves: ['d4', 'Nf6', 'c4', 'g6', 'Qc2'], name: 'Queen\'s Pawn, Mengarini Attack' },
  { moves: ['d4', 'd5', 'Nc3', 'Nf6', 'Bf4'], name: 'Rapport-Jobava System' },
  { moves: ['d4', 'd5', 'Nc3', 'e6', 'Bf4'], name: 'Rapport-Jobava System, with e6' },
  { moves: ['d4', 'Nf6', 'Nc3', 'd5', 'Bg5'], name: 'Richter-Veresov Attack' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5'], name: 'Ruy Lopez' },
  { moves: ['Nf3', 'd5', 'c4', 'c6', 'b3'], name: 'Réti Opening: Anglo-Slav Variation, Bogoljubow Variation' },
  { moves: ['c4', 'c6', 'Nf3', 'd5', 'e3'], name: 'Réti Opening: Anglo-Slav Variation, Gurevich System' },
  { moves: ['Nf3', 'd5', 'c4', 'd4', 'Rg1'], name: 'Réti Opening: Penguin Variation' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4'], name: 'Scotch Game' },
  { moves: ['e4', 'c5', 'Nc3', 'Nc6', 'Nge2'], name: 'Sicilian Defense: Closed, Chameleon Variation' },
  { moves: ['e4', 'c5', 'Nc3', 'Nc6', 'g3'], name: 'Sicilian Defense: Closed, Fianchetto Variation' },
  { moves: ['e4', 'c5', 'Nc3', 'Nc6', 'g4'], name: 'Sicilian Defense: Closed, Grob Attack' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'c3'], name: 'Sicilian Defense: Delayed Alapin Variation, with d6' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'c3'], name: 'Sicilian Defense: Delayed Alapin Variation, with e6' },
  { moves: ['e4', 'c5', 'b3', 'd5', 'Bb2'], name: 'Sicilian Defense: Euwe Attack, Prins Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'b3'], name: 'Sicilian Defense: French Variation, Westerinen Attack' },
  { moves: ['e4', 'c5', 'Nc3', 'Nc6', 'f4'], name: 'Sicilian Defense: Grand Prix Attack' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'f4'], name: 'Sicilian Defense: Halasz Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'g6', 'd4'], name: 'Sicilian Defense: Hyperaccelerated Fianchetto' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'Bd3'], name: 'Sicilian Defense: Kopec System' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'c4'], name: 'Sicilian Defense: Kramnik Variation' },
  { moves: ['e4', 'c5', 'f4', 'd5', 'Nc3'], name: 'Sicilian Defense: McDonnell Attack, Toilet Variation' },
  { moves: ['e4', 'c5', 'd4', 'cxd4', 'Nf3'], name: 'Sicilian Defense: Morphy Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'Bb5+'], name: 'Sicilian Defense: Moscow Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nf6', 'e5'], name: 'Sicilian Defense: Nimzowitsch Variation, Advance Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nf6', 'Nc3'], name: 'Sicilian Defense: Nimzowitsch Variation, Closed Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'Bb5'], name: 'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'Be2'], name: 'Sicilian Defense: O\'Kelly Variation, Aronin System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'b3'], name: 'Sicilian Defense: O\'Kelly Variation, Kieseritzky System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c4'], name: 'Sicilian Defense: O\'Kelly Variation, Maróczy Bind' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'd4'], name: 'Sicilian Defense: O\'Kelly Variation, Normal System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'd3'], name: 'Sicilian Defense: O\'Kelly Variation, Quiet System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'g3'], name: 'Sicilian Defense: O\'Kelly Variation, Réti System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'c3'], name: 'Sicilian Defense: O\'Kelly Variation, Venice System' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'b4'], name: 'Sicilian Defense: O\'Kelly Variation, Wing Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'a6', 'Nc3'], name: 'Sicilian Defense: O\'Kelly Variation, Yerevan System' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4'], name: 'Sicilian Defense: Open' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6', 'b4'], name: 'Sicilian Defense: Portsmouth Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'e6', 'b4'], name: 'Sicilian Defense: Wing Gambit Deferred' },
  { moves: ['e4', 'c5', 'b4', 'cxb4', 'Bb2'], name: 'Sicilian Defense: Wing Gambit, Abrahams Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'd6', 'b4'], name: 'Sicilian Defense: Wing Gambit, Deferred Variation' },
  { moves: ['e4', 'c5', 'b4', 'cxb4', 'a3'], name: 'Sicilian Defense: Wing Gambit, Marshall Variation' },
  { moves: ['e4', 'c5', 'b4', 'cxb4', 'c4'], name: 'Sicilian Defense: Wing Gambit, Santasiere Variation' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'e4'], name: 'Slav Defense: Diemer Gambit' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'cxd5'], name: 'Slav Defense: Exchange Variation' },
  { moves: ['d4', 'd5', 'c4', 'c6', 'Nf3'], name: 'Slav Defense: Modern Line' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Nc3'], name: 'Three Knights Opening' },
  { moves: ['d4', 'Nf6', 'Nf3', 'e6', 'Bg5'], name: 'Torre Attack: Classical Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6', 'Bg5'], name: 'Torre Attack: Fianchetto Defense' },
  { moves: ['d4', 'Nf6', 'Bg5', 'e6', 'e4'], name: 'Trompowsky Attack: Classical Defense, Big Center Variation' },
  { moves: ['d4', 'Nf6', 'Bg5', 'Ne4', 'Bh4'], name: 'Trompowsky Attack: Edge Variation' },
  { moves: ['d4', 'Nf6', 'Bg5', 'Ne4', 'h4'], name: 'Trompowsky Attack: Raptor Variation' },
  { moves: ['Nc3', 'd5', 'e4', 'dxe4', 'f3'], name: 'Van Geet Opening: Dougherty Gambit' },
  { moves: ['Nc3', 'd5', 'e4', 'dxe4', 'd3'], name: 'Van Geet Opening: Dunst-Perrenet Gambit' },
  { moves: ['Nc3', 'd5', 'e4', 'dxe4', 'Bc4'], name: 'Van Geet Opening: Hector Gambit' },
  { moves: ['Nc3', 'f5', 'e4', 'fxe4', 'd3'], name: 'Van Geet Opening: Kluever Gambit' },
  { moves: ['Nc3', 'e5', 'Nf3', 'Nc6', 'd4'], name: 'Van Geet Opening: Napoleon Attack' },
  { moves: ['Nc3', 'e5', 'f4', 'exf4', 'e4'], name: 'Van Geet Opening: Nowokunski Gambit' },
  { moves: ['Nc3', 'd5', 'd3', 'Nf6', 'g3'], name: 'Van Geet Opening: Venezolana Variation' },
  { moves: ['e3', 'e5', 'Bc4', 'b5', 'Bb3'], name: 'Van\'t Kruijs Opening: Bouncing Bishop Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6', 'f4'], name: 'Vienna Gambit, with Max Lange Defense' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6', 'd4'], name: 'Vienna Game: Fyfe Gambit' },
  { moves: ['e4', 'e5', 'Nc3', 'Bc5', 'Qg4'], name: 'Vienna Game: Giraffe Attack' },
  { moves: ['e4', 'e5', 'Nc3', 'Bc5', 'Na4'], name: 'Vienna Game: Hamppe-Meitner Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'a3'], name: 'Vienna Game: Mengarini Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'g3'], name: 'Vienna Game: Mieses Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'd6', 'f4'], name: 'Vienna Game: Omaha Gambit' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6', 'g3'], name: 'Vienna Game: Paulsen Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4'], name: 'Vienna Game: Stanley Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4'], name: 'Vienna Game: Vienna Gambit' },
  { moves: ['d4', 'Nf6', 'Nf3', 'e6', 'e3'], name: 'Yusupov-Rubinstein System' },
  { moves: ['Nf3', 'f5', 'd3', 'Nf6', 'e4'], name: 'Zukertort Opening: Lisitsyn Gambit Deferred' },
  { moves: ['Nf3', 'Nf6', 'a4', 'g6', 'b4'], name: 'Zukertort Opening: Myers Polish Attack' },
  { moves: ['Nf3', 'c5', 'd4', 'cxd4', 'e3'], name: 'Zukertort Opening: Speelsmet Gambit' },
  { moves: ['e4', 'Nf6', 'e5', 'Ng8'], name: 'Alekhine Defense: Brooklyn Variation' },
  { moves: ['e4', 'Nf6', 'e5', 'Ne4'], name: 'Alekhine Defense: Mokele Mbembe' },
  { moves: ['e4', 'Nf6', 'e5', 'Nd5'], name: 'Alekhine Defense: Normal Variation' },
  { moves: ['e4', 'Nf6', 'Nc3', 'd5'], name: 'Alekhine Defense: Scandinavian Variation' },
  { moves: ['f3', 'e5', 'g4', 'Qh4#'], name: 'Barnes Opening: Fool\'s Mate' },
  { moves: ['d4', 'Nf6', 'c4', 'c5'], name: 'Benoni Defense' },
  { moves: ['d4', 'c5', 'dxc5', 'Na6'], name: 'Benoni Defense: Benoni Gambit, Schlenker Defense' },
  { moves: ['d4', 'c5', 'd5', 'Nf6'], name: 'Benoni Defense: Benoni-Indian Defense' },
  { moves: ['d4', 'c5', 'dxc5', 'b6'], name: 'Benoni Defense: Cormorant Gambit' },
  { moves: ['d4', 'c5', 'd5', 'f5'], name: 'Benoni Defense: Old Benoni, Mujannah Formation' },
  { moves: ['d4', 'c5', 'd5', 'Na6'], name: 'Benoni Defense: Snail Variation' },
  { moves: ['f4', 'f5', 'd4', 'd5'], name: 'Bird Opening: Double Duck Formation' },
  { moves: ['f4', 'h6', 'Nf3', 'g5'], name: 'Bird Opening: Hobbs-Zilbermints Gambit' },
  { moves: ['f4', 'e5', 'fxe5', 'f6'], name: 'Bird Opening: Lasker Gambit' },
  { moves: ['f4', 'e5', 'fxe5', 'Ne7'], name: 'Bird Opening: Platz Gambit' },
  { moves: ['f4', 'e5', 'fxe5', 'Nc6'], name: 'Bird Opening: Schlechter Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'Nf6'], name: 'Bishop\'s Opening: Berlin Defense' },
  { moves: ['e4', 'e5', 'Bc4', 'Bc5'], name: 'Bishop\'s Opening: Boi Variation' },
  { moves: ['e4', 'e5', 'Bc4', 'f5'], name: 'Bishop\'s Opening: Calabrese Countergambit' },
  { moves: ['e4', 'e5', 'Bc4', 'd5'], name: 'Bishop\'s Opening: Khan Gambit' },
  { moves: ['e4', 'e5', 'Bc4', 'c6'], name: 'Bishop\'s Opening: Philidor Counterattack' },
  { moves: ['e4', 'g5', 'd4', 'e5'], name: 'Borg Defense: Zilbermints Gambit' },
  { moves: ['e4', 'c6', 'c4', 'e5'], name: 'Caro-Kann Defense: Accelerated Panov Attack, Open Variation' },
  { moves: ['e4', 'c6', 'd4', 'Na6'], name: 'Caro-Kann Defense: De Bruycker Defense' },
  { moves: ['e4', 'c6', 'd4', 'Nf6'], name: 'Caro-Kann Defense: Masi Variation' },
  { moves: ['e4', 'c6', 'd4', 'f5'], name: 'Caro-Kann Defense: Massachusetts Defense' },
  { moves: ['e4', 'h6', 'd4', 'e5'], name: 'Carr Defense: Zilbermints Gambit' },
  { moves: ['e4', 'e5', 'd4', 'exd4'], name: 'Center Game Accepted' },
  { moves: ['h3', 'd5', 'a3', 'e5'], name: 'Creepy Crawly Formation: Classical Defense' },
  { moves: ['d4', 'f5', 'c4', 'e6'], name: 'Dutch Defense: Classical Variation' },
  { moves: ['d4', 'f5', 'g4', 'e5'], name: 'Dutch Defense: Hevendehl Gambit' },
  { moves: ['d4', 'f5', 'c4', 'Nf6'], name: 'Dutch Defense: Normal Variation' },
  { moves: ['d4', 'f5', 'Nf3', 'e5'], name: 'Dutch Defense: Omega-Isis Gambit' },
  { moves: ['d4', 'f5', 'e4', 'fxe4'], name: 'Dutch Defense: Staunton Gambit Accepted' },
  { moves: ['d4', 'Nf6', 'Nf3', 'Ne4'], name: 'Döry Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'g6'], name: 'East Indian Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'd5'], name: 'Elephant Gambit' },
  { moves: ['c4', 'g6', 'e4', 'e5'], name: 'English Opening: Adorjan Defense' },
  { moves: ['c4', 'Nf6', 'Nc3', 'd5'], name: 'English Opening: Anglo-Grünfeld Defense' },
  { moves: ['c4', 'Nf6', 'Nc3', 'e6'], name: 'English Opening: Anglo-Indian Defense, Hedgehog System' },
  { moves: ['c4', 'Nf6', 'Nf3', 'g6'], name: 'English Opening: Anglo-Indian Defense, King\'s Indian Formation' },
  { moves: ['c4', 'Nf6', 'Nf3', 'd6'], name: 'English Opening: Anglo-Indian Defense, Old Indian Formation' },
  { moves: ['c4', 'Nf6', 'Nf3', 'b6'], name: 'English Opening: Anglo-Indian Defense, Queen\'s Indian Formation' },
  { moves: ['c4', 'Nf6', 'Nf3', 'd5'], name: 'English Opening: Anglo-Indian Defense, Scandinavian Defense' },
  { moves: ['c4', 'd5', 'cxd5', 'e6'], name: 'English Opening: Anglo-Scandinavian Defense, Löhn Gambit' },
  { moves: ['c4', 'd5', 'cxd5', 'Nf6'], name: 'English Opening: Anglo-Scandinavian Defense, Schulz Gambit' },
  { moves: ['c4', 'e5', 'g3', 'h5'], name: 'English Opening: Drill Variation' },
  { moves: ['c4', 'e5', 'Nc3', 'Bb4'], name: 'English Opening: King\'s English Variation, Kramnik-Shirov Counterattack' },
  { moves: ['c4', 'e5', 'Nf3', 'e4'], name: 'English Opening: King\'s English Variation, Nimzowitsch-Flohr Variation' },
  { moves: ['c4', 'e5', 'Nc3', 'Nc6'], name: 'English Opening: King\'s English Variation, Reversed Closed Sicilian' },
  { moves: ['c4', 'e5', 'Nc3', 'Nf6'], name: 'English Opening: King\'s English Variation, Two Knights Variation' },
  { moves: ['c4', 'g5', 'd4', 'Bg7'], name: 'English Opening: Myers Gambit' },
  { moves: ['c4', 'c5', 'Nc3', 'Nc6'], name: 'English Opening: Symmetrical Variation, Two Knights Variation' },
  { moves: ['c4', 'g5', 'd4', 'e5'], name: 'English Opening: Zilbermints Gambit' },
  { moves: ['d4', 'e5', 'Nf3', 'e4'], name: 'Englund Gambit Declined: Reversed Krebs' },
  { moves: ['d4', 'e5', 'dxe5', 'd6'], name: 'Englund Gambit: Hartlaub-Charlick Gambit' },
  { moves: ['d4', 'e5', 'dxe5', 'Qh4'], name: 'Englund Gambit: Mosquito Gambit' },
  { moves: ['d4', 'e5', 'dxe5', 'f6'], name: 'Englund Gambit: Soller Gambit' },
  { moves: ['e4', 'e6', 'd4', 'b5'], name: 'French Defense: Baeuerle Gambit' },
  { moves: ['e4', 'e6', 'd4', 'f5'], name: 'French Defense: Franco-Hiva Gambit' },
  { moves: ['e4', 'e6', 'd4', 'c5'], name: 'French Defense: Franco-Sicilian Defense' },
  { moves: ['e4', 'e6', 'd3', 'f5'], name: 'French Defense: King\'s Indian Attack, Franco-Hiva Gambit' },
  { moves: ['e4', 'e6', 'Nf3', 'f5'], name: 'French Defense: Knight Variation, Franco-Hiva Gambit' },
  { moves: ['e4', 'e6', 'd4', 'Nf6'], name: 'French Defense: Mediterranean Defense' },
  { moves: ['e4', 'e6', 'd4', 'a6'], name: 'French Defense: St. George Defense' },
  { moves: ['e4', 'f6', 'd4', 'Kf7'], name: 'Fried Fox Defense' },
  { moves: ['e4', 'h5', 'd4', 'Nf6'], name: 'Goldsmith Defense: Picklepuss Defense' },
  { moves: ['g4', 'd5', 'Bg2', 'c6'], name: 'Grob Opening: Grob Gambit Declined' },
  { moves: ['g4', 'e5', 'h3', 'Nc6'], name: 'Grob Opening: London Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Qe7'], name: 'Gunderam Defense' },
  { moves: ['d4', 'e6', 'c4', 'e5'], name: 'Horwitz Defense: Zilbermints Gambit' },
  { moves: ['g3', 'd5', 'Bg2', 'e6'], name: 'Hungarian Opening: Catalan Formation' },
  { moves: ['g3', 'd5', 'Bg2', 'c5'], name: 'Hungarian Opening: Reversed Modern Defense' },
  { moves: ['g3', 'd5', 'Bg2', 'c6'], name: 'Hungarian Opening: Slav Formation' },
  { moves: ['g3', 'h5', 'Nf3', 'h4'], name: 'Hungarian Opening: Van Kuijk Gambit' },
  { moves: ['g3', 'd5', 'Nf3', 'g5'], name: 'Hungarian Opening: Wiedenhagen-Beta Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'e5'], name: 'Indian Defense: Budapest Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'c6'], name: 'Indian Defense: Czech-Indian' },
  { moves: ['d4', 'Nf6', 'g4', 'Nxg4'], name: 'Indian Defense: Gibbins-Weidenhagen Gambit Accepted' },
  { moves: ['d4', 'Nf6', 'g4', 'e5'], name: 'Indian Defense: Gibbins-Weidenhagen Gambit, Oshima Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'a6'], name: 'Indian Defense: Knights Variation, Alburt-Miles Variation' },
  { moves: ['d4', 'Nf6', 'Nd2', 'e5'], name: 'Indian Defense: Lazard Gambit' },
  { moves: ['d4', 'Nf6', 'Nc3', 'e5'], name: 'Indian Defense: Maddigan Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'g5'], name: 'Indian Defense: Medusa Gambit' },
  { moves: ['d4', 'Nf6', 'Nf3', 'b5'], name: 'Indian Defense: Polish Variation' },
  { moves: ['d4', 'Nf6', 'c4', 'b5'], name: 'Indian Defense: Pyrenees Gambit' },
  { moves: ['d4', 'Nf6', 'Nc3', 'c5'], name: 'Indian Defense: Reversed Chigorin Defense' },
  { moves: ['d4', 'Nf6', 'Nf3', 'c5'], name: 'Indian Defense: Spielmann-Indian' },
  { moves: ['d4', 'Nf6', 'Nf3', 'd6'], name: 'Indian Defense: Wade-Tartakower Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'g6'], name: 'Indian Defense: West Indian Defense' },
  { moves: ['d4', 'e6', 'c4', 'Bb4+'], name: 'Kangaroo Defense' },
  { moves: ['e4', 'e5', 'f4', 'exf4'], name: 'King\'s Gambit Accepted' },
  { moves: ['e4', 'e5', 'f4', 'Bc5'], name: 'King\'s Gambit Declined: Classical Variation' },
  { moves: ['e4', 'e5', 'f4', 'd5'], name: 'King\'s Gambit Declined: Falkbeer Countergambit' },
  { moves: ['e4', 'e5', 'f4', 'Qh4+'], name: 'King\'s Gambit Declined: Keene\'s Defense' },
  { moves: ['e4', 'c5', 'f4', 'e5'], name: 'King\'s Gambit Declined: Mafia Defense' },
  { moves: ['e4', 'e5', 'f4', 'Qf6'], name: 'King\'s Gambit Declined: Norwalde Variation' },
  { moves: ['e4', 'e5', 'f4', 'f5'], name: 'King\'s Gambit Declined: Panteldakis Countergambit' },
  { moves: ['e4', 'e5', 'f4', 'Nf6'], name: 'King\'s Gambit Declined: Petrov\'s Defense' },
  { moves: ['e4', 'e5', 'f4', 'Nc6'], name: 'King\'s Gambit Declined: Queen\'s Knight Defense' },
  { moves: ['e4', 'e5', 'f4', 'g5'], name: 'King\'s Gambit Declined: Zilbermints Double Countergambit' },
  { moves: ['Nf3', 'd5', 'g3', 'g6'], name: 'King\'s Indian Attack: Double Fianchetto' },
  { moves: ['Nf3', 'd5', 'g3', 'Bg4'], name: 'King\'s Indian Attack: Keres Variation' },
  { moves: ['Nf3', 'd5', 'g3', 'e5'], name: 'King\'s Indian Attack: Omega-Delta Gambit' },
  { moves: ['Nf3', 'd5', 'g3', 'c5'], name: 'King\'s Indian Attack: Sicilian Variation' },
  { moves: ['Nf3', 'Nf6', 'g3', 'b5'], name: 'King\'s Indian Attack: Spassky Variation' },
  { moves: ['Nf3', 'Nf6', 'g3', 'g6'], name: 'King\'s Indian Attack: Symmetrical Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nc6'], name: 'King\'s Knight Opening: Normal Variation' },
  { moves: ['e4', 'e5', 'c4', 'd5'], name: 'King\'s Pawn Game: Bavarian Gambit' },
  { moves: ['e4', 'e5', 'd4', 'd5'], name: 'King\'s Pawn Game: Beyer Gambit' },
  { moves: ['e4', 'e5', 'Nf3', 'Bc5'], name: 'King\'s Pawn Game: Busch-Gass Gambit' },
  { moves: ['e4', 'e5', 'd3', 'f5'], name: 'King\'s Pawn Game: Clam Variation, King\'s Gambit Reversed' },
  { moves: ['e4', 'e5', 'Nf3', 'f6'], name: 'King\'s Pawn Game: Damiano Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'c6'], name: 'King\'s Pawn Game: Gunderam Gambit' },
  { moves: ['e4', 'e5', 'c3', 'f5'], name: 'King\'s Pawn Game: MacLeod Attack, Lasa Gambit' },
  { moves: ['e4', 'd6', 'd4', 'e5'], name: 'King\'s Pawn Game: Maróczy Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Qf6'], name: 'King\'s Pawn Game: McConnell Defense' },
  { moves: ['e4', 'e5', 'Qh5', 'Nf6'], name: 'King\'s Pawn Game: Wayward Queen Attack, Kiddie Countergambit' },
  { moves: ['e4', 'e5', 'Nf3', 'f5'], name: 'Latvian Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'Nc6'], name: 'Mexican Defense' },
  { moves: ['e4', 'g6', 'd4', 'f5'], name: 'Modern Defense: Fianchetto Gambit' },
  { moves: ['e4', 'g6', 'd4', 'Nf6'], name: 'Modern Defense: Norwegian Defense' },
  { moves: ['d4', 'Nc6', 'd5', 'Nb8'], name: 'Montevideo Defense' },
  { moves: ['e4', 'Nc6', 'Nf3', 'f5'], name: 'Nimzowitsch Defense: Colorado Countergambit' },
  { moves: ['e4', 'Nc6', 'Nf3', 'e6'], name: 'Nimzowitsch Defense: Franco-Nimzowitsch Variation' },
  { moves: ['e4', 'Nc6', 'Nc3', 'e6'], name: 'Nimzowitsch Defense: French Connection' },
  { moves: ['e4', 'Nc6', 'd4', 'e5'], name: 'Nimzowitsch Defense: Kennedy Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'd6'], name: 'Nimzowitsch Defense: Mikenas Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'f6'], name: 'Nimzowitsch Defense: Neo-Mongoloid Defense' },
  { moves: ['e4', 'Nc6', 'Nc3', 'g6'], name: 'Nimzowitsch Defense: Pirc Connection' },
  { moves: ['e4', 'Nc6', 'd4', 'd5'], name: 'Nimzowitsch Defense: Scandinavian Variation' },
  { moves: ['e4', 'Nc6', 'Nf3', 'd6'], name: 'Nimzowitsch Defense: Williams Variation' },
  { moves: ['e4', 'Nc6', 'd4', 'a6'], name: 'Nimzowitsch Defense: Woodchuck Variation' },
  { moves: ['e4', 'b6', 'd4', 'Ba6'], name: 'Owen Defense: Guatemala Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'Nf6'], name: 'Petrov\'s Defense' },
  { moves: ['e4', 'e5', 'Nf3', 'd6'], name: 'Philidor Defense' },
  { moves: ['b4', 'd5', 'Bb2', 'Bf5'], name: 'Polish Opening: Baltic Defense' },
  { moves: ['b4', 'e5', 'Bb2', 'd6'], name: 'Polish Opening: Czech Defense' },
  { moves: ['b4', 'd5', 'Bb2', 'Qd6'], name: 'Polish Opening: German Defense' },
  { moves: ['b4', 'Nf6', 'Bb2', 'g6'], name: 'Polish Opening: King\'s Indian Variation' },
  { moves: ['b4', 'e5', 'Bb2', 'c5'], name: 'Polish Opening: Wolferts Gambit' },
  { moves: ['d4', 'Nf6', 'Nf3', 'b6'], name: 'Pseudo Queen\'s Indian Defense' },
  { moves: ['d4', 'd5', 'c4', 'dxc4'], name: 'Queen\'s Gambit Accepted' },
  { moves: ['d4', 'd5', 'c4', 'e6'], name: 'Queen\'s Gambit Declined' },
  { moves: ['d4', 'd5', 'c4', 'e5'], name: 'Queen\'s Gambit Declined: Albin Countergambit' },
  { moves: ['d4', 'd5', 'c4', 'c5'], name: 'Queen\'s Gambit Declined: Austrian Defense' },
  { moves: ['d4', 'd5', 'c4', 'Bf5'], name: 'Queen\'s Gambit Declined: Baltic Defense' },
  { moves: ['d4', 'd5', 'c4', 'Nc6'], name: 'Queen\'s Gambit Declined: Chigorin Defense' },
  { moves: ['d4', 'd5', 'c4', 'Nf6'], name: 'Queen\'s Gambit Declined: Marshall Defense' },
  { moves: ['d4', 'd5', 'c4', 'b5'], name: 'Queen\'s Gambit Declined: Zilbermints Gambit' },
  { moves: ['d4', 'Nf6', 'c4', 'b6'], name: 'Queen\'s Indian Accelerated' },
  { moves: ['d4', 'd5', 'Bf4', 'c5'], name: 'Queen\'s Pawn Game: Accelerated London System, Steinitz Countergambit' },
  { moves: ['d4', 'c6', 'c4', 'd6'], name: 'Queen\'s Pawn Game: Anglo-Slav Opening' },
  { moves: ['Nf3', 'd5', 'd4', 'Bg4'], name: 'Queen\'s Pawn Game: Anti-Torre' },
  { moves: ['d4', 'd5', 'Nc3', 'Bf5'], name: 'Queen\'s Pawn Game: Chigorin Variation, Alburt Defense' },
  { moves: ['d4', 'd5', 'Nc3', 'Bg4'], name: 'Queen\'s Pawn Game: Chigorin Variation, Anti-Veresov' },
  { moves: ['d4', 'd5', 'Nc3', 'c5'], name: 'Queen\'s Pawn Game: Chigorin Variation, Irish Gambit' },
  { moves: ['d4', 'd5', 'Nc3', 'e5'], name: 'Queen\'s Pawn Game: Chigorin Variation, Shaviliuk Gambit' },
  { moves: ['d4', 'd5', 'Nc3', 'h5'], name: 'Queen\'s Pawn Game: Chigorin Variation, Shropshire Defense' },
  { moves: ['d4', 'd5', 'Nf3', 'c5'], name: 'Queen\'s Pawn Game: Krause Variation' },
  { moves: ['d4', 'd5', 'Bg5', 'Bg4'], name: 'Queen\'s Pawn Game: Levitsky Attack, Welling Variation' },
  { moves: ['d4', 'd5', 'Nf3', 'Nf6'], name: 'Queen\'s Pawn Game: Symmetrical Variation' },
  { moves: ['d4', 'f5', 'Nc3', 'd5'], name: 'Queen\'s Pawn Game: Veresov Attack, Dutch System' },
  { moves: ['e4', 'd6', 'd4', 'Nd7'], name: 'Rat Defense: Antal Defense' },
  { moves: ['e4', 'd6', 'd4', 'f5'], name: 'Rat Defense: Balogh Defense' },
  { moves: ['d4', 'd6', 'c4', 'e5'], name: 'Rat Defense: English Rat' },
  { moves: ['d4', 'e6', 'e4', 'd6'], name: 'Rat Defense: Small Center Defense' },
  { moves: ['Nf3', 'd5', 'c4', 'd4'], name: 'Réti Opening: Advance Variation' },
  { moves: ['Nf3', 'd5', 'c4', 'dxc4'], name: 'Réti Opening: Réti Accepted' },
  { moves: ['Nf3', 'd5', 'c4', 'b5'], name: 'Réti Opening: Zilbermints Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'c6'], name: 'Scandinavian Defense: Blackburne-Kloosterboer Gambit' },
  { moves: ['e4', 'd5', 'exd5', 'Qxd5'], name: 'Scandinavian Defense: Mieses-Kotroc Variation' },
  { moves: ['e4', 'd5', 'exd5', 'Nf6'], name: 'Scandinavian Defense: Modern Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'f5'], name: 'Sicilian Defense: Brussels Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'h6'], name: 'Sicilian Defense: Bücker Variation' },
  { moves: ['e4', 'c5', 'Nc3', 'Nc6'], name: 'Sicilian Defense: Closed, Traditional' },
  { moves: ['e4', 'c5', 'Nf3', 'e6'], name: 'Sicilian Defense: French Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'g6'], name: 'Sicilian Defense: Hyperaccelerated Dragon' },
  { moves: ['e4', 'c5', 'Nf3', 'e5'], name: 'Sicilian Defense: Jalalabad Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'b6'], name: 'Sicilian Defense: Katalimov Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'd6'], name: 'Sicilian Defense: Modern Variations' },
  { moves: ['e4', 'c5', 'Nf3', 'Qa5'], name: 'Sicilian Defense: Mongoose Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nf6'], name: 'Sicilian Defense: Nimzowitsch Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'a6'], name: 'Sicilian Defense: O\'Kelly Variation' },
  { moves: ['e4', 'c5', 'Nf3', 'Nc6'], name: 'Sicilian Defense: Old Sicilian' },
  { moves: ['e4', 'c5', 'Nf3', 'b5'], name: 'Sicilian Defense: Polish Gambit' },
  { moves: ['e4', 'c5', 'Nf3', 'Qc7'], name: 'Sicilian Defense: Quinteros Variation' },
  { moves: ['e4', 'c5', 'b3', 'b6'], name: 'Sicilian Defense: Snyder Variation, Queen Fianchetto Variation' },
  { moves: ['d4', 'd5', 'c4', 'c6'], name: 'Slav Defense' },
  { moves: ['d4', 'Nf6', 'c4', 'c6'], name: 'Slav Indian' },
  { moves: ['e4', 'a6', 'd4', 'e5'], name: 'St. George Defense: Zilbermints Gambit' },
  { moves: ['d4', 'Nf6', 'Bg5', 'e6'], name: 'Trompowsky Attack: Classical Defense' },
  { moves: ['Nc3', 'e5', 'Nf3', 'Bc5'], name: 'Van Geet Opening: Billockus-Johansen Gambit' },
  { moves: ['Nc3', 'd5', 'f4', 'e5'], name: 'Van Geet Opening: Damhaug Gambit' },
  { moves: ['Nc3', 'd5', 'f4', 'g5'], name: 'Van Geet Opening: Warsteiner Gambit' },
  { moves: ['e4', 'e5', 'Nc3', 'Bc5'], name: 'Vienna Game: Anderssen Defense' },
  { moves: ['e4', 'e5', 'Nc3', 'Nf6'], name: 'Vienna Game: Falkbeer Variation' },
  { moves: ['e4', 'e5', 'Nc3', 'Nc6'], name: 'Vienna Game: Max Lange Defense' },
  { moves: ['d4', 'd6', 'Nf3', 'Bg4'], name: 'Wade Defense' },
  { moves: ['e4', 'a5', 'd4', 'Nc6'], name: 'Ware Defense: Snagglepuss Defense' },
  { moves: ['a4', 'b5', 'axb5', 'Bb7'], name: 'Ware Opening: Wing Gambit' },
  { moves: ['Nf3', 'Nh6', 'd4', 'g6'], name: 'Zukertort Defense: Kingside Variation' },
  { moves: ['Nf3', 'Na6', 'e4', 'c5'], name: 'Zukertort Defense: Sicilian Knight Variation' },
  { moves: ['Nf3', 'Na6', 'e4', 'Nh6'], name: 'Zukertort Opening: Drunken Cavalry Variation' },
  { moves: ['Nf3', 'd6', 'd4', 'e5'], name: 'Zukertort Opening: Vos Gambit' },
  { moves: ['Nf3', 'd6', 'e4', 'Bg4'], name: 'Zukertort Opening: Wade Defense' },
  { moves: ['e4', 'Nf6', 'Bc4'], name: 'Alekhine Defense: Krejcik Variation' },
  { moves: ['e4', 'Nf6', 'd3'], name: 'Alekhine Defense: Maróczy Variation' },
  { moves: ['d4', 'd5', 'Qd3'], name: 'Amazon Attack' },
  { moves: ['a3', 'a5', 'b4'], name: 'Anderssen\'s Opening: Polish Gambit' },
  { moves: ['f3', 'e5', 'Kf2'], name: 'Barnes Opening: Hammerschlag' },
  { moves: ['d4', 'c5', 'dxc5'], name: 'Benoni Defense: Benoni Gambit Accepted' },
  { moves: ['d4', 'c5', 'b4'], name: 'Benoni Defense: Zilbermints-Benoni Gambit' },
  { moves: ['f4', 'd5', 'g4'], name: 'Bird Opening: Dutch Variation, Dudweiler Gambit' },
  { moves: ['f4', 'e5', 'Nc3'], name: 'Bird Opening: From\'s Gambit, Bahr Gambit' },
  { moves: ['f4', 'Nf6', 'c4'], name: 'Bird Opening: Mujannah' },
  { moves: ['f4', 'd5', 'c4'], name: 'Bird Opening: Sturm Gambit' },
  { moves: ['f4', 'f5', 'e4'], name: 'Bird Opening: Wagner-Zwitersch Gambit' },
  { moves: ['f4', 'd5', 'e4'], name: 'Bird Opening: Williams Gambit' },
  { moves: ['e4', 'e5', 'Bc4'], name: 'Bishop\'s Opening' },
  { moves: ['d4', 'd5', 'e4'], name: 'Blackmar-Diemer Gambit' },
  { moves: ['e4', 'e5', 'Ke2'], name: 'Bongcloud Attack' },
  { moves: ['d4', 'Nf6', 'f4'], name: 'Canard Opening' },
  { moves: ['e4', 'c6', 'c4'], name: 'Caro-Kann Defense: Accelerated Panov Attack' },
  { moves: ['e4', 'c6', 'd3'], name: 'Caro-Kann Defense: Breyer Variation' },
  { moves: ['e4', 'c6', 'b3'], name: 'Caro-Kann Defense: Euwe Attack' },
  { moves: ['e4', 'c6', 'Bc4'], name: 'Caro-Kann Defense: Hillbilly Attack' },
  { moves: ['e4', 'c6', 'b4'], name: 'Caro-Kann Defense: Labahn Attack' },
  { moves: ['e4', 'c6', 'g4'], name: 'Caro-Kann Defense: Spike Variation' },
  { moves: ['e4', 'e5', 'd4'], name: 'Center Game' },
  { moves: ['h3', 'h5', 'g4'], name: 'Clemenz Opening: Spike Lee Gambit' },
  { moves: ['d4', 'f5', 'Qd3'], name: 'Dutch Defense: Alapin Variation' },
  { moves: ['d4', 'f5', 'g3'], name: 'Dutch Defense: Fianchetto Attack' },
  { moves: ['d4', 'f5', 'Bg5'], name: 'Dutch Defense: Hopton Attack' },
  { moves: ['d4', 'f5', 'h3'], name: 'Dutch Defense: Korchnoi Attack' },
  { moves: ['d4', 'f5', 'g4'], name: 'Dutch Defense: Krejcik Gambit' },
  { moves: ['d4', 'f5', 'Nc3'], name: 'Dutch Defense: Raphael Variation' },
  { moves: ['d4', 'f5', 'e4'], name: 'Dutch Defense: Staunton Gambit' },
  { moves: ['c4', 'Nf6', 'e4'], name: 'English Opening: Achilles-Omega Gambit' },
  { moves: ['c4', 'f5', 'e4'], name: 'English Opening: Anglo-Dutch Defense, Hickmann Gambit' },
  { moves: ['c4', 'Nf6', 'Nf3'], name: 'English Opening: Anglo-Indian Defense, King\'s Knight Variation' },
  { moves: ['c4', 'Nf6', 'Nc3'], name: 'English Opening: Anglo-Indian Defense, Queen\'s Knight Variation' },
  { moves: ['c4', 'e5', 'Nf3'], name: 'English Opening: King\'s English Variation, Nimzowitsch Variation' },
  { moves: ['c4', 'e5', 'Nc3'], name: 'English Opening: King\'s English Variation, Reversed Sicilian' },
  { moves: ['c4', 'c5', 'Nc3'], name: 'English Opening: Symmetrical Variation, Normal Variation' },
  { moves: ['e4', 'e5', 'c4'], name: 'English Opening: The Whale' },
  { moves: ['c4', 'f5', 'g4'], name: 'English Opening: Wade Gambit' },
  { moves: ['c4', 'c5', 'b4'], name: 'English Opening: Wing Gambit' },
  { moves: ['c4', 'Nf6', 'b4'], name: 'English Orangutan' },
  { moves: ['d4', 'e5', 'd5'], name: 'Englund Gambit Declined' },
  { moves: ['d4', 'e5', 'Nf3'], name: 'Englund Gambit Declined: Reversed Alekhine' },
  { moves: ['d4', 'e5', 'e3'], name: 'Englund Gambit Declined: Reversed French' },
  { moves: ['e4', 'e6', 'b4'], name: 'French Defense: Banzai-Leong Gambit' },
  { moves: ['e4', 'e6', 'Bb5'], name: 'French Defense: Bird Invitation' },
  { moves: ['e4', 'e6', 'Qe2'], name: 'French Defense: Chigorin Variation' },
  { moves: ['e4', 'e6', 'b3'], name: 'French Defense: Horwitz Attack' },
  { moves: ['e4', 'e6', 'd3'], name: 'French Defense: King\'s Indian Attack' },
  { moves: ['e4', 'e6', 'Nf3'], name: 'French Defense: Knight Variation' },
  { moves: ['e4', 'e6', 'f4'], name: 'French Defense: La Bourdonnais Variation' },
  { moves: ['e4', 'e6', 'd4'], name: 'French Defense: Normal Variation' },
  { moves: ['e4', 'e6', 'Nc3'], name: 'French Defense: Queen\'s Knight' },
  { moves: ['e4', 'e6', 'g3'], name: 'French Defense: Réti-Spielmann Attack' },
  { moves: ['e4', 'e6', 'c4'], name: 'French Defense: Steiner Variation' },
  { moves: ['e4', 'e6', 'e5'], name: 'French Defense: Steinitz Attack' },
  { moves: ['h3', 'e5', 'a3'], name: 'Global Opening' },
  { moves: ['g4', 'g5', 'f4'], name: 'Grob Opening: Double Grob, Coca-Cola Gambit' },
  { moves: ['g4', 'd5', 'Bg2'], name: 'Grob Opening: Grob Gambit' },
  { moves: ['g3', 'e5', 'Nf3'], name: 'Hungarian Opening: Reversed Alekhine' },
  { moves: ['d4', 'Nf6', 'Bf4'], name: 'Indian Defense: Accelerated London System' },
  { moves: ['d4', 'Nf6', 'g4'], name: 'Indian Defense: Gibbins-Weidenhagen Gambit' },
  { moves: ['d4', 'Nf6', 'Nf3'], name: 'Indian Defense: Knights Variation' },
  { moves: ['d4', 'Nf6', 'c4'], name: 'Indian Defense: Normal Variation' },
  { moves: ['d4', 'Nf6', 'e4'], name: 'Indian Defense: Omega Gambit' },
  { moves: ['d4', 'Nf6', 'd5'], name: 'Indian Defense: Pawn Push Variation' },
  { moves: ['d4', 'Nf6', 'g3'], name: 'Indian Defense: Tartakower Attack' },
  { moves: ['e4', 'e5', 'f4'], name: 'King\'s Gambit' },
  { moves: ['Nf3', 'd5', 'g3'], name: 'King\'s Indian Attack' },
  { moves: ['e4', 'e5', 'Nf3'], name: 'King\'s Knight Opening' },
  { moves: ['e4', 'e5', 'Ne2'], name: 'King\'s Pawn Game: Alapin Opening' },
  { moves: ['e4', 'e5', 'f3'], name: 'King\'s Pawn Game: King\'s Head Opening' },
  { moves: ['e4', 'e5', 'd3'], name: 'King\'s Pawn Game: Leonardis Variation' },
  { moves: ['e4', 'e5', 'c3'], name: 'King\'s Pawn Game: MacLeod Attack' },
  { moves: ['e4', 'e5', 'a3'], name: 'King\'s Pawn Game: Mengarini\'s Opening' },
  { moves: ['e4', 'e5', 'Qf3'], name: 'King\'s Pawn Game: Napoleon Attack' },
  { moves: ['e4', 'e5', 'Bd3'], name: 'King\'s Pawn Game: Tortoise Opening' },
  { moves: ['e4', 'e5', 'Qh5'], name: 'King\'s Pawn Game: Wayward Queen Attack' },
  { moves: ['e4', 'e5', 'b3'], name: 'King\'s Pawn Opening' },
  { moves: ['h4', 'd5', 'Rh3'], name: 'Kádas Opening: Beginner\'s Trap' },
  { moves: ['h4', 'c5', 'b4'], name: 'Kádas Opening: Kádas Gambit' },
  { moves: ['d3', 'g6', 'g4'], name: 'Mieses Opening: Myers Spike Attack' },
  { moves: ['b3', 'd5', 'Ba3'], name: 'Nimzo-Larsen Attack: Graz Attack' },
  { moves: ['e4', 'Nc6', 'Nf3'], name: 'Nimzowitsch Defense: Declined Variation' },
  { moves: ['e4', 'Nc6', 'Bb5'], name: 'Nimzowitsch Defense: Pseudo-Spanish Variation' },
  { moves: ['e4', 'Nc6', 'b4'], name: 'Nimzowitsch Defense: Wheeler Gambit' },
  { moves: ['d4', 'd6', 'c4'], name: 'Old Indian Defense' },
  { moves: ['d4', 'Nf6', 'f3'], name: 'Paleface Attack' },
  { moves: ['b4', 'e5', 'a3'], name: 'Polish Opening: Bugayev Attack' },
  { moves: ['e4', 'e5', 'Bb5'], name: 'Portuguese Opening' },
  { moves: ['d4', 'd5', 'c4'], name: 'Queen\'s Gambit' },
  { moves: ['d4', 'd5', 'Bf4'], name: 'Queen\'s Pawn Game: Accelerated London System' },
  { moves: ['d4', 'd5', 'Nc3'], name: 'Queen\'s Pawn Game: Chigorin Variation' },
  { moves: ['d4', 'd5', 'Bg5'], name: 'Queen\'s Pawn Game: Levitsky Attack' },
  { moves: ['d4', 'd5', 'f4'], name: 'Queen\'s Pawn Game: Mason Attack' },
  { moves: ['d4', 'd5', 'Nf3'], name: 'Queen\'s Pawn Game: Zukertort Variation' },
  { moves: ['d4', 'd5', 'g4'], name: 'Queen\'s Pawn Game: Zurich Gambit' },
  { moves: ['e4', 'd6', 'f4'], name: 'Rat Defense: Harmonist' },
  { moves: ['e4', 'd6', 'h4'], name: 'Rat Defense: Petruccioli Attack' },
  { moves: ['e4', 'd6', 'g4'], name: 'Rat Defense: Spike Attack' },
  { moves: ['Nf3', 'd5', 'c4'], name: 'Réti Opening' },
  { moves: ['e4', 'd5', 'b4'], name: 'Scandinavian Defense: Zilbermints Gambit' },
  { moves: ['e4', 'c5', 'c3'], name: 'Sicilian Defense: Alapin Variation' },
  { moves: ['e4', 'c5', 'Qg4'], name: 'Sicilian Defense: Amazon Attack' },
  { moves: ['e4', 'c5', 'Bc4'], name: 'Sicilian Defense: Bowdler Attack' },
  { moves: ['e4', 'c5', 'Nh3'], name: 'Sicilian Defense: Brick Variation' },
  { moves: ['e4', 'c5', 'Nc3'], name: 'Sicilian Defense: Closed' },
  { moves: ['e4', 'c5', 'g4'], name: 'Sicilian Defense: Grob Variation' },
  { moves: ['e4', 'c5', 'Ne2'], name: 'Sicilian Defense: Keres Variation' },
  { moves: ['e4', 'c5', 'Ke2'], name: 'Sicilian Defense: King David\'s Opening' },
  { moves: ['e4', 'c5', 'Na3'], name: 'Sicilian Defense: Kronberger Variation' },
  { moves: ['e4', 'c5', 'g3'], name: 'Sicilian Defense: Lasker-Dunne Attack' },
  { moves: ['e4', 'c5', 'f4'], name: 'Sicilian Defense: McDonnell Attack' },
  { moves: ['e4', 'c5', 'a3'], name: 'Sicilian Defense: Mengarini Variation' },
  { moves: ['e4', 'c5', 'a4'], name: 'Sicilian Defense: Myers Attack, with a4' },
  { moves: ['e4', 'c5', 'h4'], name: 'Sicilian Defense: Myers Attack, with h4' },
  { moves: ['e4', 'c5', 'd4'], name: 'Sicilian Defense: Smith-Morra Gambit' },
  { moves: ['e4', 'c5', 'b3'], name: 'Sicilian Defense: Snyder Variation' },
  { moves: ['e4', 'c5', 'c4'], name: 'Sicilian Defense: Staunton-Cochrane Variation' },
  { moves: ['e4', 'c5', 'b4'], name: 'Sicilian Defense: Wing Gambit' },
  { moves: ['Na3', 'g6', 'g4'], name: 'Sodium Attack: Chenoboskion Variation' },
  { moves: ['d4', 'Nf6', 'Bg5'], name: 'Trompowsky Attack' },
  { moves: ['d3', 'e5', 'Nd2'], name: 'Valencia Opening' },
  { moves: ['a3', 'e5', 'Nc3'], name: 'Van Geet Opening: Battambang Variation' },
  { moves: ['Nc3', 'c5', 'b4'], name: 'Van Geet Opening: Düsseldorf Gambit' },
  { moves: ['Nc3', 'g6', 'h4'], name: 'Van Geet Opening: Myers Attack' },
  { moves: ['Nc3', 'c5', 'Rb1'], name: 'Van Geet Opening: Twyble Attack' },
  { moves: ['Nc3', 'Nf6', 'g4'], name: 'Van Geet Opening: Tübingen Gambit' },
  { moves: ['e4', 'e5', 'Nc3'], name: 'Vienna Game' },
  { moves: ['a4', 'e5', 'h4'], name: 'Ware Opening: Crab Variation' },
  { moves: ['a4', 'e5', 'Ra3'], name: 'Ware Opening: Meadow Hay Trap' },
  { moves: ['Nf3', 'd5', 'Rg1'], name: 'Zukertort Opening: Ampel Variation' },
  { moves: ['Nf3', 'Nf6', 'e4'], name: 'Zukertort Opening: Lemberger Gambit' },
  { moves: ['Nf3', 'f5', 'e4'], name: 'Zukertort Opening: Lisitsyn Gambit' },
  { moves: ['Nf3', 'Nf6', 'b3'], name: 'Zukertort Opening: Nimzo-Larsen Variation' },
  { moves: ['Nf3', 'd5', 'd3'], name: 'Zukertort Opening: Old Indian Attack' },
  { moves: ['Nf3', 'Nf6', 'e3'], name: 'Zukertort Opening: Quiet System' },
  { moves: ['Nf3', 'd5', 'Nc3'], name: 'Zukertort Opening: Reversed Mexican Defense' },
  { moves: ['b4', 'd5', 'Nf3'], name: 'Zukertort Opening: Santasiere\'s Folly' },
  { moves: ['e4', 'd5', 'Nf3'], name: 'Zukertort Opening: Tennison Gambit' },
  { moves: ['Nf3', 'd5', 'a4'], name: 'Zukertort Opening: The Potato' },
  { moves: ['e4', 'Nf6'], name: 'Alekhine Defense' },
  { moves: ['d4', 'Na6'], name: 'Australian Defense' },
  { moves: ['e4', 'f6'], name: 'Barnes Defense' },
  { moves: ['d4', 'c5'], name: 'Benoni Defense: Old Benoni' },
  { moves: ['f4', 'd5'], name: 'Bird Opening: Dutch Variation' },
  { moves: ['f4', 'e5'], name: 'Bird Opening: From\'s Gambit' },
  { moves: ['f4', 'g5'], name: 'Bird Opening: Hobbs Gambit' },
  { moves: ['f4', 'Nh6'], name: 'Bird Opening: Horsefly Defense' },
  { moves: ['f4', 'b5'], name: 'Bird Opening: Myers Defense' },
  { moves: ['e4', 'g5'], name: 'Borg Defense' },
  { moves: ['d4', 'g5'], name: 'Borg Defense: Borg Gambit' },
  { moves: ['e4', 'c6'], name: 'Caro-Kann Defense' },
  { moves: ['e4', 'h6'], name: 'Carr Defense' },
  { moves: ['e4', 'f5'], name: 'Duras Gambit' },
  { moves: ['d4', 'f5'], name: 'Dutch Defense' },
  { moves: ['d4', 'b6'], name: 'English Defense' },
  { moves: ['c4', 'e6'], name: 'English Opening: Agincourt Defense' },
  { moves: ['c4', 'f5'], name: 'English Opening: Anglo-Dutch Defense' },
  { moves: ['c4', 'Nf6'], name: 'English Opening: Anglo-Indian Defense' },
  { moves: ['c4', 'Nc6'], name: 'English Opening: Anglo-Lithuanian Variation' },
  { moves: ['c4', 'd5'], name: 'English Opening: Anglo-Scandinavian Defense' },
  { moves: ['c4', 'c6'], name: 'English Opening: Caro-Kann Defensive System' },
  { moves: ['c4', 'g6'], name: 'English Opening: Great Snake Variation' },
  { moves: ['c4', 'b5'], name: 'English Opening: Jaenisch Gambit' },
  { moves: ['c4', 'e5'], name: 'English Opening: King\'s English Variation' },
  { moves: ['c4', 'g5'], name: 'English Opening: Myers Defense' },
  { moves: ['c4', 'c5'], name: 'English Opening: Symmetrical Variation' },
  { moves: ['d4', 'e5'], name: 'Englund Gambit' },
  { moves: ['e4', 'e6'], name: 'French Defense' },
  { moves: ['e4', 'h5'], name: 'Goldsmith Defense' },
  { moves: ['g4', 'f5'], name: 'Grob Opening: Alessi Gambit' },
  { moves: ['g4', 'g5'], name: 'Grob Opening: Double Grob' },
  { moves: ['e4', 'Nh6'], name: 'Hippopotamus Defense' },
  { moves: ['d4', 'e6'], name: 'Horwitz Defense' },
  { moves: ['g3', 'f5'], name: 'Hungarian Opening: Dutch Defense' },
  { moves: ['g3', 'Nf6'], name: 'Hungarian Opening: Indian Defense' },
  { moves: ['g3', 'g5'], name: 'Hungarian Opening: Myers Defense' },
  { moves: ['g3', 'c5'], name: 'Hungarian Opening: Sicilian Invitation' },
  { moves: ['g3', 'g6'], name: 'Hungarian Opening: Symmetrical Variation' },
  { moves: ['d4', 'Nf6'], name: 'Indian Defense' },
  { moves: ['h4', 'a5'], name: 'Kádas Opening: Koola-Koola Variation' },
  { moves: ['h4', 'g5'], name: 'Kádas Opening: Schneider Gambit' },
  { moves: ['g3', 'h5'], name: 'Lasker Simul Special' },
  { moves: ['e4', 'Na6'], name: 'Lemming Defense' },
  { moves: ['d3', 'e5'], name: 'Mieses Opening: Reversed Rat' },
  { moves: ['d4', 'Nc6'], name: 'Mikenas Defense' },
  { moves: ['e4', 'g6'], name: 'Modern Defense' },
  { moves: ['b3', 'd5'], name: 'Nimzo-Larsen Attack: Classical Variation' },
  { moves: ['b3', 'f5'], name: 'Nimzo-Larsen Attack: Dutch Variation' },
  { moves: ['b3', 'c5'], name: 'Nimzo-Larsen Attack: English Variation' },
  { moves: ['b3', 'Nf6'], name: 'Nimzo-Larsen Attack: Indian Variation' },
  { moves: ['b3', 'e5'], name: 'Nimzo-Larsen Attack: Modern Variation' },
  { moves: ['b3', 'b5'], name: 'Nimzo-Larsen Attack: Polish Variation' },
  { moves: ['b3', 'b6'], name: 'Nimzo-Larsen Attack: Symmetrical Variation' },
  { moves: ['e4', 'Nc6'], name: 'Nimzowitsch Defense' },
  { moves: ['e4', 'b6'], name: 'Owen Defense' },
  { moves: ['e4', 'd6'], name: 'Pirc Defense' },
  { moves: ['d4', 'b5'], name: 'Polish Defense' },
  { moves: ['b4', 'd5'], name: 'Polish Opening, with d5' },
  { moves: ['b4', 'c5'], name: 'Polish Opening: Birmingham Gambit' },
  { moves: ['b4', 'f5'], name: 'Polish Opening: Dutch Defense' },
  { moves: ['b4', 'Nc6'], name: 'Polish Opening: Grigorian Variation' },
  { moves: ['b4', 'Nh6'], name: 'Polish Opening: Karniewski Variation' },
  { moves: ['b4', 'c6'], name: 'Polish Opening: Outflank Variation' },
  { moves: ['b4', 'b5'], name: 'Polish Opening: Symmetrical Variation' },
  { moves: ['d4', 'g6'], name: 'Queen\'s Pawn Game: Modern Defense' },
  { moves: ['e4', 'd5'], name: 'Scandinavian Defense' },
  { moves: ['e4', 'c5'], name: 'Sicilian Defense' },
  { moves: ['e4', 'a6'], name: 'St. George Defense' },
  { moves: ['Nc3', 'b5'], name: 'Van Geet Opening: Laroche Gambit' },
  { moves: ['Nc3', 'e5'], name: 'Van Geet Opening: Reversed Nimzowitsch' },
  { moves: ['e4', 'a5'], name: 'Ware Defense' },
  { moves: ['a4', 'a5'], name: 'Ware Opening: Symmetric Variation' },
  { moves: ['Nf3', 'f6'], name: 'Zukertort Opening: Arctic Defense' },
  { moves: ['Nf3', 'h6'], name: 'Zukertort Opening: Basman Defense' },
  { moves: ['Nf3', 'Nc6'], name: 'Zukertort Opening: Black Mustang Defense' },
  { moves: ['Nf3', 'f5'], name: 'Zukertort Opening: Dutch Variation' },
  { moves: ['Nf3', 'g5'], name: 'Zukertort Opening: Herrstrom Gambit' },
  { moves: ['Nf3', 'g6'], name: 'Zukertort Opening: Kingside Fianchetto' },
  { moves: ['Nf3', 'd6'], name: 'Zukertort Opening: Pirc Invitation' },
  { moves: ['Nf3', 'b5'], name: 'Zukertort Opening: Polish Defense' },
  { moves: ['Nf3', 'e6'], name: 'Zukertort Opening: Queen\'s Gambit Invitation' },
  { moves: ['Nf3', 'b6'], name: 'Zukertort Opening: Queenside Fianchetto Variation' },
  { moves: ['Nf3', 'e5'], name: 'Zukertort Opening: Ross Gambit' },
  { moves: ['Nf3', 'c5'], name: 'Zukertort Opening: Sicilian Invitation' },
  { moves: ['Nf3', 'c6'], name: 'Zukertort Opening: Slav Invitation' },
  { moves: ['Nf3', 'a6'], name: 'Zukertort Opening: St. George Defense' },
  { moves: ['Nf3', 'a5'], name: 'Zukertort Opening: Ware Defense' },
  { moves: ['Nh3'], name: 'Amar Opening' },
  { moves: ['a3'], name: 'Anderssen\'s Opening' },
  { moves: ['f3'], name: 'Barnes Opening' },
  { moves: ['f4'], name: 'Bird Opening' },
  { moves: ['h3'], name: 'Clemenz Opening' },
  { moves: ['c4'], name: 'English Opening' },
  { moves: ['g4'], name: 'Grob Opening' },
  { moves: ['g3'], name: 'Hungarian Opening' },
  { moves: ['e4'], name: 'King\'s Pawn Game' },
  { moves: ['h4'], name: 'Kádas Opening' },
  { moves: ['d3'], name: 'Mieses Opening' },
  { moves: ['b3'], name: 'Nimzo-Larsen Attack' },
  { moves: ['b4'], name: 'Polish Opening' },
  { moves: ['d4'], name: 'Queen\'s Pawn Game' },
  { moves: ['c3'], name: 'Saragossa Opening' },
  { moves: ['Na3'], name: 'Sodium Attack' },
  { moves: ['Nc3'], name: 'Van Geet Opening' },
  { moves: ['e3'], name: 'Van\'t Kruijs Opening' },
  { moves: ['a4'], name: 'Ware Opening' },
  { moves: ['Nf3'], name: 'Zukertort Opening' },
]

/**
 * Given the SAN move history, return the most specific opening name,
 * or null if no opening is recognised.
 *
 * Only active during the first 15 full moves (30 half-moves).
 */
export function detectOpening(history: string[]): string | null {
  if (history.length === 0 || history.length > 30) return null

  const historyStr = history.join(' ')
  for (const opening of OPENINGS) {
    const prefix = opening.moves.join(' ')
    if (historyStr === prefix || historyStr.startsWith(prefix + ' ')) {
      return opening.name
    }
  }
  return null
}
